### ISSUE TITLE
Bundled Version of Serpico

### ISSUE THREAD

**Issue by BuffaloWill** [SerpicoProject/Serpico#104]
This issue is meant to keep track of creating a bundled version of Serpico that does not require downloading dependencies. Not sure about the feasibility of it.

Considering:
Phusion Traveling Ruby: https://github.com/phusion/traveling-ruby/
"[Traveling Ruby] allows Ruby app developers to bundle these binaries with their Ruby app, so that they can distribute a single package to end users, without needing end users to first install Ruby or gems."

**Comment by ncolyer-r7** [comment]
Any considerations for maybe a docker image?

**Comment by ncolyer-r7** [comment]
I know it is not a bundled version but I had interest in having a Docker image and created a recipe for anyone else interested.

```

# Packages & Environment Variables
ENV SRP_ROOT /Serpico
ENV GEM /usr/local/rvm/rubies/ruby-2.1.5/bin/gem
ENV BUILD_PACKAGES bash sudo curl vim git gawk g++ gcc make libc6-dev libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgmp-dev libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev

# Install Packages
RUN apt-get update && \
    apt-get install -y $BUILD_PACKAGES
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Pull Down Serpico
RUN git clone https://github.com/MooseDojo/Serpico
WORKDIR $SRP_ROOT

# Install Ruby
RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
RUN curl -L https://get.rvm.io | bash -s stable
RUN /bin/bash -l -c "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
RUN /bin/bash -l -c rvm requirements
RUN /bin/bash --login -c "source /usr/local/rvm/scripts/rvm"
ENV PATH /usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN rvm install 2.1.5 && rvm use 2.1.5
RUN rvm all do gem install bundler

# Install Required Gems
RUN /bin/bash --login -c "bundle install"

# Expose TCP:443
RUN sed -i -e 's/"port":"8443",/"port":"443",/g' $SRP_ROOT/config.json
EXPOSE 443

```

Call the docker container `docker run -it <image-id> /bin/bash -l` without the l flag, you will need to source the `/usr/local/rvm/scripts/rvm` on shell login before `ruby scripts/first_time.rb` and subsequently `ruby serpico.rb&`

**Comment by BuffaloWill** [comment]
@ncolyer-r7 sorry for the slow reply, was out most of this week. This is great!! Just tested, worked for me. 

I added a wiki entry for running from Docker. Please make recommendations if I messed something up:
https://github.com/MooseDojo/Serpico/wiki/Running-Serpico-From-Docker

**Comment by ncolyer-r7** [comment]
No worries man, glad you were cool with it. Everything looks good to me.

**Comment by Petessss** [comment]
beta deb install has been create. Needs to be tested and vetted. 
https://github.com/SerpicoProject/Serpico-Installers

I'll get cracking on a windows Version.

**Comment by BuffaloWill** [comment]
@Petessss you rock. I am going to close this issue. I am breaking this out into the following issues:

- Windows Installer (https://github.com/SerpicoProject/Serpico/issues/133)
- OSX Installer (https://github.com/SerpicoProject/Serpico/issues/134)
- Add Installer to Releases (https://github.com/SerpicoProject/Serpico/issues/135)
- Update README (https://github.com/SerpicoProject/Serpico/issues/136)
