### ISSUE TITLE
Sorting reports by user and date range in UI.

### ISSUE THREAD

**Issue by nanotechz9l** [SerpicoProject/Serpico#109]
This is an ideal feature when trying to find a specific report for a user or date range.

**Comment by BuffaloWill** [comment]
I agree having sorting (and searching) on the report page would be helpful. Search for findings was added just using JS, I think we could do something similar for searching.

**Comment by BuffaloWill** [comment]
Updating this to default sort by newest report first

**Comment by BuffaloWill** [comment]
Merged
