### ISSUE TITLE
Support Metasploit Connector

### ISSUE THREAD

**Issue by muk302** [SerpicoProject/Serpico#114]
nmap scan results
nikto scan results

This is a great tool.

**Comment by Petessss** [comment]
Hello muk302, 
 Can you please provide more detail about what you are looking for with the nmap and nikto importers? Are you wanting the results to be parsed and added as findings or something along those lines? 

Thank you.

**Comment by LibertyUnix** [comment]
That feature would be awesome! Love this project so far, great work.

**Comment by muk302** [comment]
Yes, import finding/results.

I suppose it would be easy enough to edit the exported document. But, I
think the more information that becomes part of the Serpico dataset the
better.

-Muk

**Comment by BuffaloWill** [comment]
I am thinking we could put a dent into supporting other tools through scripting. I added some example scripts here:

https://github.com/MooseDojo/Serpico/wiki/Automating-Serpico

One of which is to import data from another tool into Serpico. A similar approach could be taken for nmap or nikto.

**Comment by muk302** [comment]
I would be fine with the scripting approach. In my case, not all potential
users have a scripting/dev background. I could fix that as well, but I'd be
wrapping ruby with Python since I have little time to ramp up on ruby at
the moment. Maybe I could use your existing API's with Python? Could open a
can of worms...

**Comment by BuffaloWill** [comment]
Placing this under the umbrella of support for metasploit import

**Comment by ccammilleri** [comment]
@BuffaloWill please assign to me.

I'll update this issue soon with my engineering notes.

**Comment by BuffaloWill** [comment]
Landed. Awesome!
