### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jvoisin** [SerpicoProject/Serpico#131]
It seems that there are some issue with the setup process of Serpico. Since I don't know anything about ruby, here is a rough excerpt of my shell history showing the issue, and how I solved it : it looks like a Gemfile-related issue:

```bash
$ rvm install ruby-2.1.5
$ source /home/jvoisin/.rvm/scripts/rvm
$ gem install bundler
$ bundle install
$ ruby ./scripts/first_time.rb
/home/jvoisin/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- data_mapper (LoadError)
	from /home/jvoisin/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jvoisin/Serpico/model/master.rb:2:in `<top (required)>'
	from /home/jvoisin/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jvoisin/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./scripts/first_time.rb:8:in `<main>'
zsh: exit 1     ruby ./scripts/first_time.rb
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
bundler (1.12.5)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
$ gem install data_mapper dm-sqlite-adapter zipruby
$ scripts/first_time.rb
No users in the database, creating a first user. 
Please enter username (default: administrator):  

Generating random password and adding the Administrator with username administrator...
Please use the following login credentials
	 	 	 ****  administrator : ---------------- ****
Would you like to initialize the database with templated findings? (Y/n)

Importing Templated Findings template_findings.json...
Adding the Default Generic Risk Scoring Report Template
Adding the Default DREAD Report Template
Adding the Default CVSS Report Template
Adding the Serpico Default Finding Template
Adding the Serpico Default Status Template
Creating self-signed SSL certificate, you should really have a legitimate one.
```

**Comment by BuffaloWill** [comment]
Hi @jvoisin! My guess is `bundle install` install didn't run correctly the first time. The three gems you mentioned are included the Gemfile. 

```
$ grep -e data_mapper -e dm-sqlite-adapter -e zipruby Gemfile
gem 'zipruby', '0.3.6'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
```

Cheers!

**Comment by jvoisin** [comment]
There is nothing that you can do to fix this?
I could reproduce this behaviour on different machines :/

**Comment by Petessss** [comment]
@jvoisin, 
 Can you send us the full output when you run bundle install?

**Comment by gottasrt4** [comment]
sorry to revive such an old and dead thread, but I'm experiencing this issue, as well.  

bundle install output:

C:\Sites\todo\bin>bundle install
The dependency activerecord-jdbc-adapter (~> 1.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency activerecord-jdbcmysql-adapter (~> 1.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency activerecord-jdbcpostgresql-adapter (~> 1.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency activerecord-jdbcsqlite3-adapter (~> 1.3) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jdbc-mysql (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jdbc-sqlite3 (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jdbc-postgres (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jruby-openssl (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency trinidad (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby, x86-mingw32 but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Fetching gem metadata from https://rubygems.org/.............
rails (4.2.0) has dependency bundler (< 2.0, >= 1.3.0), which is unsatisfied by the current bundler version 2.0.1, so the dependency is being ignored
Using rake 10.4.2
Installing i18n 0.7.0
Installing json 1.8.2 with native extensions
Installing minitest 5.5.0
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.2.0
Installing builder 3.2.2
Installing erubis 2.7.0
Fetching mini_portile2 2.1.0
Installing mini_portile2 2.1.0
Fetching nokogiri 1.6.8.1 (x86-mingw32)
Installing nokogiri 1.6.8.1 (x86-mingw32)
Installing rails-deprecated_sanitizer 1.0.3
Installing rails-dom-testing 1.0.5
Installing loofah 2.0.1
Installing rails-html-sanitizer 1.0.1
Installing actionview 4.2.0
Installing rack 1.6.0
Installing rack-test 0.6.2
Installing actionpack 4.2.0
Installing globalid 0.3.0
Installing activejob 4.2.0
Installing mime-types 2.4.3
Installing mail 2.6.3
Installing actionmailer 4.2.0
Installing activemodel 4.2.0
Installing arel 6.0.0
Installing activerecord 4.2.0
Using bundler 2.0.1
Installing coffee-script-source 1.8.0
Installing execjs 2.2.2
Installing coffee-script 2.3.0
Installing thor 0.19.1
Installing railties 4.2.0
Installing coffee-rails 4.1.0
Installing ey_config 0.0.7
Installing hike 1.2.3
Installing jquery-rails 4.0.3
Installing multi_json 1.10.1
Using pg 0.21.0 (x86-mingw32)
Installing tilt 1.4.1
Installing sprockets 2.12.3
Installing sprockets-rails 2.2.2
Installing rails 4.2.0
Installing rails_autolink 1.1.6
Installing sass 3.4.9
Installing sass-rails 5.0.1
Installing simple_form 3.1.0
Using sqlite3 1.3.13 (x86-mingw32)
Fetching tzinfo-data 1.2017.2
Installing tzinfo-data 1.2017.2
Installing uglifier 2.6.1
Updating files in vendor/cache
  * mini_portile2-2.1.0.gem
  * nokogiri-1.6.8.1-x86-mingw32.gem
  * pg-0.21.0-x86-mingw32.gem
  * sqlite3-1.3.13-x86-mingw32.gem
  * tzinfo-data-1.2017.2.gem
Removing outdated .gem files from vendor/cache
  * mini_portile-0.6.2.gem
  * nokogiri-1.6.5.gem
  * pg-0.18.1.gem
  * sqlite3-1.3.10.gem
Bundle complete! 31 Gemfile dependencies, 50 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from nokogiri:
Nokogiri is built with the packaged libraries: libxml2-2.9.4, libxslt-1.1.29, zlib-1.2.8, libiconv-1.14.

**Comment by gottasrt4** [comment]
read the error and tried fixing the install, here's my output:

c:\Sites\todo\bin>bundle lock --add-platform java
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2.0) was resolved to 4.2.0, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails
(~> 4.2.0)', in any of the sources.

c:\Sites\todo\bin>gem install bundler
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Done installing documentation for bundler after 9 seconds
1 gem installed

c:\Sites\todo\bin>bundle lock --add-platform java
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies.....
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2.0) was resolved to 4.2.0, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails
(~> 4.2.0)', in any of the sources.

**Comment by Petessss** [comment]
What are you trying to accomplish?

**Comment by gottasrt4** [comment]
Install Serpico on a Windows 10 box with the Windows-Linux Subsystem (WSL) installed and enabled.  
With Warm Regards,

~Bryce Mitchell, GPENU.S. Navy Veteran 

    On Friday, April 19, 2019, 5:17:22 PM EDT, Peter <notifications@github.com> wrote:  
 
 
What are you trying to accomplish?

**Comment by Petessss** [comment]
Never tried to install under WSL. We'll have to look into that. Have you tried the windows installer? 
https://github.com/SerpicoProject/Serpico/releases/tag/1.3.0
