### ISSUE TITLE
Inconsistent display of cvss settings

### ISSUE THREAD

**Issue by ccammilleri** [SerpicoProject/Serpico#132]
There are some elsif statements that are causing this behaviour. Also errors on creation of new findings. Feel free to assign to me and I can fix.

This raises a question. Shall we support the use of dread AND cvss simultaneously? I vote yes. If we decide not to we should change the configuration to only allow one or the other.

**Comment by BuffaloWill** [comment]
The multiple scoring system approach was a poorly thought out and quickly implemented addition by me. There are a few things that bug me about it:
- It's not intuitive that the report template should match the scoring system. For example, if I switch to CVSS I need to also switch the report used on every assessment. 
- To your point, the configuration options are ~~unclear~~ broken and only one one scoring system should be used. I think we should fix this first and then approach allowing multi scoring system. The configuration change for one scoring system is easy to make. Multi scoring requires more thought and definitely updates to the UI.

Created two new findings for the bugs and change config options:
https://github.com/SerpicoProject/Serpico/issues/137
https://github.com/SerpicoProject/Serpico/issues/138

**Comment by Petessss** [comment]
@ccammilleri is this still an issue?
