### ISSUE TITLE
Create Windows Installer

### ISSUE THREAD

**Issue by BuffaloWill** [SerpicoProject/Serpico#133]
Forking from https://github.com/SerpicoProject/Serpico/issues/104; create a windows installer available for the releases tab.

**Comment by Petessss** [comment]
There is an issue with ZipRuby on Windows. Trying to work that out.

**Comment by Petessss** [comment]
blocked by zipruby. Need to look at swapping out zipruby for rubyzip.

**Comment by Petessss** [comment]
done.
