### ISSUE TITLE
Report by Assessment type

### ISSUE THREAD

**Issue by roobixx** [SerpicoProject/Serpico#142]
Im trying to create a template that reports findings by the assessment type eg: External, Internal, etc and cant seem to figure out how to accomplish this using the meta language.  Anytime I try to do a string comparison for say ¬report/findings_list/findings:::risk>3:::assessment_type='External'¬ it throws an error. ' #<RuntimeError: compilation error: element if xsl:if : could not compile test expression 'assessment_type=’external’' > '

Goal:

External Assessment
-Findings
--Critical
...
Internal Assessment
-Findings
--Critical
...

**Comment by BuffaloWill** [comment]
@roobixx this should work:
```
¬report/findings_list/findings:::risk>3¬
† translate(assessment_type,$up,$low)=translate('External',$up,$low) †
FINDINGS
¥
```
Still working on a better way to do string comparison, https://github.com/SerpicoProject/Serpico/issues/121.

Sorry for the late reply.

**Comment by roobixx** [comment]
Thank you so much! I will try this out.

Going to go ahead and close the issue.

**Comment by pentestgou1** [comment]
¬report/findings_list/findings:::risk>3¬
† translate(assessment_type,$up,$low)=translate('External',$up,$low) †
FINDINGS
¥ 

Is there a better way to compare strings developt?
