### ISSUE TITLE
Markdown editor support with upload images option

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#143]
Creating an issue as per discussion during BH Arsenal.

Issues description and other text area's can benfit from having a javascript markdown editor, this if coupled with upload images option will also streamline the whole markdown editing process.

some sample java-script markdown editors : 
https://simplemde.com
https://vuejs.org/examples/

**Comment by BuffaloWill** [comment]
Moving to a plugin. JS based markup in general could be augmented.
