### ISSUE TITLE
startup script initrd / upstart / systemd / service for  installer

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#144]
Creating an issue as per discussion during BH Arsenal.

The installer should install Serpico as a service.
1) initrd / upstart / systemd config for linux
2) service install for Windows 
3) service or simmilar install for mac.

this will ensure that start stop restart is smooth, if you add logging code a seperate log file could be created with debug logs etc.

**Comment by BuffaloWill** [comment]
@Petessss, any updates on this?

**Comment by Petessss** [comment]
Almost done. Dealing with Sinatra's crazy out. Once that's fixed, I'll push the updated.

**Comment by Petessss** [comment]
https://github.com/SerpicoProject/Serpico/pull/160 - pull request created.

**Comment by Petessss** [comment]
updates pushed.
