### ISSUE TITLE
Peer review inside finding details

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#145]
Creating an issue as per discussion during BH Arsenal.

An option for peer review within the reporting too. 
1) when a user can mark a report done and available for review, 
2) another user pick's up and performs changes and mark it as reviewed. 
3) Original user gets a notification that its done review and in updated report user can see the differences / changes being made and may be accept or reject individual changes.

**Comment by BuffaloWill** [comment]
@anantshri, to update you. In discussions with @Petessss about how to fit this in and possible plugin architecture.

**Comment by Petessss** [comment]
Now that the plugin framework is available this would make a great addition.  If you have any questions or need any assistance let us know.
