### ISSUE TITLE
markdown sanity check per issues save

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#146]
Creating an issue as per discussion during BH Arsenal.

When an individual issue is saved a markdown sanity check should be called and should be used to pick bad markdown.

**Comment by BuffaloWill** [comment]
Dev notes:
I think two updates should be sufficient:
1. Add a new method to helper.rb with a sanity check
2. Modify all routes that post to :findings_edit or :findings_add with the check
