### ISSUE TITLE
export database with attachments

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#147]
Creating an issue as per discussion during BH Arsenal.

Right now json doesn't contains attachments, what about adding one of the two options

1) a large / massive json blob with all attachments base64'ed inside it.
2) a zip download  and simmilarly upload option to ensure all attachments are extracted and restored correctly.

**Comment by BuffaloWill** [comment]
@Petessss, any updates on this?

**Comment by Petessss** [comment]
Its still in progress.

**Comment by Petessss** [comment]
Pull request created. If the method looks good, I'll add some error checking and clean things up.

**Comment by Petessss** [comment]
Updates pushed.
