### ISSUE TITLE
Low severity and info issues from Nessus XML are not populating in serpico findings

### ISSUE THREAD

**Issue by rajdaggubati** [SerpicoProject/Serpico#150]
Few issues when I import Nessus xml:

1. I only see critical issues in Serpico but not the info and medium issues.

2. I also observed drop in the findings count( Nessus has 7 findings and i only see 6 in Serpico) . 

What i am doing wrong?

**Comment by BuffaloWill** [comment]
Hi @rajdaggubati. Serpico defaults to this setting when importing Nessus XML. To change, go to Administration > Configuration Settings and modify the threshold to a lower number (e.g. 0 to include informational findings). You will then want to re-import your findings.
