### ISSUE TITLE
any option to add custom user editable field

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#151]
I am looking at adding a custom user editable field in each report. Say a field XYZ predefined but user editable in the form. There is an option to have custom user defined variable but that needs to be created everytime i dont want to rely on user creating that field everytime. 

We can compare this to say the fields like customer phone email etc.

**Comment by BuffaloWill** [comment]
@anantshri, there is a Global User Defined Variable in the configuration settings. This should add the UDV to every new report. Does this work?

**Comment by Petessss** [comment]
@anantshri, did this answer your question?

**Comment by marcbyky** [comment]
Is it possible to add a custom fields for the findings? I would like to add an Impact as well as a Status and Scope field.
