### ISSUE TITLE
Simple Risk Rating Format

### ISSUE THREAD

**Issue by infosecrepo** [SerpicoProject/Serpico#153]
It would be great to be able to use just a simple risk rating format. More specifically, the following, as commonly used by many organizations:

Risk = Impact x Likelihood

Thank you!

**Comment by BuffaloWill** [comment]
@infosecrepo, I think PR 152 (https://github.com/SerpicoProject/Serpico/pull/152) is similar to what you are looking for. Does this fit? Still performing code review on it but it should land soon.

**Comment by infosecrepo** [comment]
I'm no ruby expert... but looking at the code changes from #152, it does seem to match my request. Thanks!

**Comment by BuffaloWill** [comment]
Apologies, I was being lazy; should've added more detail about the PR. PR152 adds an additional scoring format where you can set a severity and likelihood on a finding. The risk for the finding is then calculated as

Risk = Severity + Likelihood

**Comment by infosecrepo** [comment]
No worries, I was able to get the idea. I may have some suggested changes once #152 is merged.
