### ISSUE TITLE
Filter by Assessment Type

### ISSUE THREAD

**Issue by chandooz** [SerpicoProject/Serpico#154]
I was wondering if there was a way to filter by assessment type much like you can for the Dread Score (i.e. :::assessment_type=External)? Is there a way to do this?

**Comment by chandooz** [comment]
I saw that someone already answered this so I'd like to adjust the question. Is it possible to do it in a  table?

**Comment by BuffaloWill** [comment]
Hi @chandooz! 

Yes, it is possible to do this in a table. The code is very similar:
```
æfindings_list/findings:::risk<5:::translate(assessment_type,$up,$low)=translate('external',$up,$low)æ ∞title∞
```

**Comment by BuffaloWill** [comment]
Added a wiki page:
https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report

**Comment by chandooz** [comment]
It didn't work for me, but by adding report to the beginning it did. æreport/findings_list/findings....

**Comment by chandooz** [comment]
Thank you for your help!

**Comment by BuffaloWill** [comment]
My bad! Thanks, I will update the wiki.
