### ISSUE TITLE
Screenshots are not being exported to Serpico report

### ISSUE THREAD

**Issue by harithanalluri** [SerpicoProject/Serpico#158]
Screenshots are not being exported:
 1. Observed that the tool is not exporting the screenshots in to the report
 2. I did follow the instructions specified in the Wiki page "Inserting Screenshots" ---->[!! sqli.png !!]
 3. Is there anything more to be done?

Thank you.

**Comment by Petessss** [comment]
@harithanalluri, can you please provide more information? What type of image are you using? How is the image named? Do you have spaces, dashes in the name? Which version of Serpico are you using (installer or direct from github)?

**Comment by Petessss** [comment]
@harithanalluri if this is still an issue please reopen.
