### ISSUE TITLE
'Notes' information is not being exported to Serpico Report

### ISSUE THREAD

**Issue by harithanalluri** [SerpicoProject/Serpico#159]
'Notes' information is not being exported:
 1. Observed that the 'Notes' content of Findings is not being exported to the report. 
 2. Is there any way to export the 'Notes', as it is important to give IP/Port details in the report on need basis.

Thank you.

**Comment by Petessss** [comment]
This is correct. The notes were intended for internal use only. The "
Affected Hosts/URLs" section can be used for IP/Port details.
