### ISSUE TITLE
passwd reset

### ISSUE THREAD

**Issue by yashar6909** [SerpicoProject/Serpico#161]
When the database was created it generated a password for me, 
now my machine crashed (not serpico's fault) and I didn't have time to reset or change the password.
I have looked at the script reset_pw.rb , but executing it with ruby does not seem to work.
Do you have an easier way of doing this? as I have started to write extensive information that I do not particularly want to lose :)

**Comment by Petessss** [comment]
@yashar6909 Can you please provide more information? How are you running the script? What output does the script give. Which version of Serpico are you running, the installer or development?

**Comment by BuffaloWill** [comment]
Hey @yashar6909. I have run into this on the installer version. If this is the case for you, this script should work:
[reset_pass.sh](https://gist.githubusercontent.com/BuffaloWill/aecd5473a8d7540e8f4ddb226c1ff901/raw/b2b7212f6d43bea6d327a600202366f291567ba5/reset_pass.sh)

To use:
```
cd /opt/Serpico
curl -o reset_pass.sh https://gist.githubusercontent.com/BuffaloWill/aecd5473a8d7540e8f4ddb226c1ff901/raw/b2b7212f6d43bea6d327a600202366f291567ba5/reset_pass.sh
chmod +x reset_pass.sh
./reset_pass.sh administrator [NEW_PASS]
```

**Comment by Petessss** [comment]
@BuffaloWill I have added that script to the omnibus packages.

**Comment by BuffaloWill** [comment]
Thanks @Petessss! Closing the issue, @yashar6909 please reopen if that doesn't work for you.
