### ISSUE TITLE
Could not import all the Nessuss findings into Serpico

### ISSUE THREAD

**Issue by harithanalluri** [SerpicoProject/Serpico#163]
Not able to see all the Nessus findings in Serpico UI

1. Trying to import findings from Nessus(.nessus XML file) to Serpico.
2. Some of the findings are missing in Serpico UI and subsequently in the Serpico report.
3. Eg: If I import 7 medium findings from a Nessus report, I could see only 6 in Serpico GUI (both in the Graph and also in the list of findings)
4. I did set 'auto import' and also mapped the corresponding mapping (in this case Nessus: 'nessusmap').
5. Please let me know what am I missing here.

**Comment by Petessss** [comment]
@harithanalluri, Can you please provide more information about your setup, vuln mappings and whatnot? There is not enough information in your posts to help us figure out that the issue is.

Thanks.

**Comment by BuffaloWill** [comment]
@harithanalluri have you set the threshold setting in the configuration to 0? This will cause not all issues to be imported.

**Comment by BuffaloWill** [comment]
@harithanalluri -- Have you updated to the latest code and modified the threshold? Please re-open if this is still an issue.
