### ISSUE TITLE
Affected hosts/urls not imported into report

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#164]
1. I am performing a network scan ,where  each IP would get a different set of vulnerabilities.
2. To generate a report I need Affected Hosts/URLs field to be imported into report.
3. Affected Hosts/URLs are displayed in GUI but not in the report.
4. Please let me know if there is any way to import Affected Hosts/URLs field to Serpico report

**Comment by Petessss** [comment]
@shalinich, check out the new Metasploit connector. see if that helps with your situation.
