### ISSUE TITLE
Nessus findings are not imported into Serpico

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#165]
1. All the findings from Nessus are not imported into Serpico.
2. If there were 7 findings then I could get only 6(number varies if has more findings).
3. Even these finding are not listed in Serpico GUI.
4. I want all the findings in Nessus to be imported into Serpico.
5. Let me know if I am missing something.

**Comment by Petessss** [comment]
@shalinich, Can you please provide more information about your setup, vuln mappings and whatnot? There is not enough information in your posts to help us figure out that the issue is. 

Thanks.

**Comment by shalinich** [comment]
vulnmap in configuration settings is unchecked.
Even if I check the vulnmap and  click on save ,it is still unchecked.
Rest all of the options in configuration menu were checked.
Let me know if I should configure anything else

**Comment by shalinich** [comment]
I am importing a .nessus file and giving it as an input to generate report.
In configuration settings I checked all the check boxes including vulnmap,ssl e.t.c
I have downloaded the nessus file from some other system and uploaded it.
Is there any thing else I need to configure??

**Comment by BuffaloWill** [comment]
Have you modified the threshold setting? This value should be set to 0.

If this doesn't solve the problem you will need to send a copy of your Nessus data for us to recreate the issue as it sounds specific to the data you are importing. Please redact the data before sending.

**Comment by Petessss** [comment]
@shalinich, can you please git pull the latest code and try again? There was a fix on July 30 for a vuln map bug. (https://github.com/SerpicoProject/Serpico/commit/73d62de98bcb873cbc8a1cead1daa7f6796b7605)

Thanks

**Comment by BuffaloWill** [comment]
@shalinich -- Have you updated to the latest code and modified the threshold? Please re-open if this is still an issue.
