### ISSUE TITLE
Unable to find docker image.

### ISSUE THREAD

**Issue by parag85** [SerpicoProject/Serpico#166]
![docker_1](https://cloud.githubusercontent.com/assets/8840359/18283094/5449a390-7481-11e6-9f64-8a5f280f5802.JPG)

**Comment by BuffaloWill** [comment]
hi @parag85! you have a typo. It should be
```
ncolyer/serpico
```
not
```
ncloyer/serpico
```

https://hub.docker.com/r/ncolyer/serpico/
