### ISSUE TITLE
Metasploit  RPC Connection

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#169]
1. How do we configure metasploit RPC connection in Serpico?
2. Which credentials should I give to establish a connection ?
3. Connection is not been established properly,I am unable to import findings from metasploit db??
4. Let me know how to establish a connection?

**Comment by Petessss** [comment]
@shalinich, use the following to configure the Metasploit RPC connector under Serpico:
1) Logged in as an Administrator, Under the "Maintenance Menu" on the Left hand side of the screen, select "Modify Configuration" 
2) Make sure "vulnmap" is enabled.
3) Next access the report for which you want to configure the Metasploit RPC connector for.
4) On the Left hand side select "Additional Features"
5) Under Additional Features select "Configure a Metasploit RPC Connection"
6) Updates the Metasploit RPC Settings with the reverent data. 
7) Similar to the Nessus import you will have to setup your vulnerability mappings.
8) Now you can use the "Hosts and Vulnerabilities" menus under Metasploit Data Management menu.  

As for setting up Metasploit see the wiki https://github.com/rapid7/metasploit-framework/wiki
