### ISSUE TITLE
Display Specific Finding

### ISSUE THREAD

**Issue by chandooz** [SerpicoProject/Serpico#171]
If I wanted to display the information from one specific finding in the report, is there a way to do that? Say for example I have 5 findings, but I only want to display the name and description of one specific finding in a certain portion of the report.

**Comment by BuffaloWill** [comment]
Thanks @chandooz. You should be able to do this with a string comparison but need to test. I think this will tie in with https://github.com/SerpicoProject/Serpico/issues/121

**Comment by chandooz** [comment]
Okay sounds good.

**Comment by BuffaloWill** [comment]
No longer handling this through GH. E-mail support or IRC can help for specific template questions.
