### ISSUE TITLE
Space In Report Title

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#172]
[Issue] - Creating a new report with a space in the title causes a dump.

Actions:
Create New Report
Set Title of report with a space, e.g., "New Report 101"

Result:
Web Application throws error. The new report is made however.

**Comment by Petessss** [comment]
Can you please past the dump?

**Comment by aconite33** [comment]
Interesting, I just tried to reproduce this. I'll verify with a brand new install and see if I can get it to give me a crash.

**Comment by Petessss** [comment]
Can you provide more info about your setup? Are you running the latest code? What OS are you running on? I entered the same information from your screenshot, but was unable to reproduce the crash.

**Comment by aconite33** [comment]
OS: Kali Linux, Rolling. x64
Ruby version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Serpico Version: Latest Git Pull

OS: Ubuntu 16.04 x64
Ruby version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Serpico Version: Latest Git Pull

**Comment by Petessss** [comment]
A, can you try with ruby 2.1.5. Serpico has not be tested with Ruby 2.3.1.
