### ISSUE TITLE
Informational is not an available risk level

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#173]
Modifying/editing a new finding, you cannot identify a risk as information. The only available levels are:

Critical
High
Moderate
Low

Yet the default template allows for informational (risk = 0).

**Comment by BuffaloWill** [comment]
IIRC 0 (Informational) was removed because it was causing issues with score conversions to other metrics. Let me take a look at this again.

reference for later:
findings_edit.haml (ln 296)

**Comment by aoighost** [comment]
Could this please be implemented as an optional then, or at least an idea given in what needs to be added to add the functionality in a fork?

**Comment by BuffaloWill** [comment]
This will make it into the next release. In the mean time, it should be in the master branch within the next three weeks.

**Comment by BuffaloWill** [comment]
Just landed; @aoighost @aconite33
