### ISSUE TITLE
Adding  Affected Hosts/URLs in Serpico report

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#177]
Affected hosts/URL s are displayed in preview of vulnerability .
I want the same field in Serpico report also.
Can we add it by using meta language.
My report would be incomplete without Affected Hosts/URL s field
Please let me know if I am missing any thing AND let me know if I can modify the base template

**Comment by Petessss** [comment]
@shalinich, you will need to add the following meta language to the preview template and report template.

<img width="287" alt="affected-hosts" src="https://cloud.githubusercontent.com/assets/16560500/18473834/a5329af2-7984-11e6-97c8-d1dd1b5f125b.png">

For more information on the meta language please see https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth.

Please reopen if this does not address your question.

**Comment by shalinich** [comment]
If I modify the content in template,then generate report is displaying the below error,even if I am modifying that with original template it is displaying the below error.

**Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.**

How do i rectify this error???
