### ISSUE TITLE
Log LDAP Authentication Errors

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#178]
Is there a way to turn on verbose logging? I'm trying to get LDAP (Active Directory) authentication to work, but I want to see the errors to find what authentication problems I'm having.

**Comment by BuffaloWill** [comment]
hi @aconite33. There is only one level of logging and IMO it's already verbose. That being said, this issue seems specific to LDAP auth. Reviewing the code, Serpico silently fails on an LDAP auth failure. We should be writing the LDAP auth error to the logs.

**Comment by aconite33** [comment]
Roger. Change in title is fine.
For setting up LDAP correctly, I'm using:
ldap_domain: domain.com
ldap_dc: domain_controller.domain.com

That should allow me to authenticate to LDAP (Active Directory type)?

**Comment by BuffaloWill** [comment]
That should be correct. The port is hardcoded to 636 and requires SSL.

**Comment by aconite33** [comment]
Hmm, I've got that configuration set, and Port 636 is open from Seprico Server -> AD and no joy. Do I need to login with something like DomainName\UserName? Or just UserName? Both are not working.

**Comment by BuffaloWill** [comment]
just username is good, the code concats the domain for you (e.g. domain\user)

**Comment by aconite33** [comment]
Okay, gotcha. I can't seem to get mine to work. So having the logging of the LDAP auth would be helpful to determine what is causing my error.

**Comment by BuffaloWill** [comment]
pushed.
