### ISSUE TITLE
Default findings template uses <<COMPANY>> instead of <<CUSTOMER>>

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#181]
The default finding templates for "Excessive Ingress Rule Set" and "Open Mail Relay Identified" use `&lt;&lt;COMPANY&gt;&gt` instead of `&lt;&lt;CUSTOMER&gt;&gt`

This causes the <<COMPANY>> to be left unreplaced in the final report.

**Comment by BuffaloWill** [comment]
Landed.
