### ISSUE TITLE
Adding Affected Hosts/URLs in Serpico report

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#183]
If I modify the content in template with below content,

**Affected hosts**
**π  affected_hosts/paragraphπ**

Then generate report is displaying the below error,

**Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.**

How do i rectify this error???

**Comment by Petessss** [comment]
That usually means you have something wrong with your markup. Two questions:
1) Are you using Microsoft Word? 
2) Are there any errors on the console or error log when you generate the report?

**Comment by jstangle** [comment]
I would recommend you edit it just in Microsoft Word. LibreOffice could make there some mistakes. I added this to template and it works well:

**Affected Hosts/URL
¬affected_hosts/paragraph¬ µzzzzµ π.π
÷ π.π ≠**

Let try it.

**Comment by BuffaloWill** [comment]
@jstangle, good find on the references issue. The references requiring multiple lines is a bug; I'll create a separate issue to track it there.

@shalinich LibreOffice is not supported. Attempting to upload a template created in LibreOffice will be a mess.

**Comment by shalinich** [comment]
Thanks for the reply.Its working fine now using Microsoft word.
