### ISSUE TITLE
Encryption - Client Data

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#186]
Does Serpico have any encryption of the client data/report? It would be nice if we could state that our reporting utility that houses client data is stored in an encrypted / protected format.

**Comment by BuffaloWill** [comment]
hi @aconite33, the expectation is that the user maintains the Serpico dir as encrypted or with FDE. If you are on Kali, this should be handled for you. Personally, I use cryptsetup to (un)mount and FDE for the drive.
