### ISSUE TITLE
Modifying A User's Role Resets Their Password

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#188]
When modifying/editing a user, if you change their role, e.g., from user to Admin, their password no longer works. Requires the user to be reset.

**Comment by BuffaloWill** [comment]
@aconite33, let me look into this. I'll update the issue.

**Comment by BuffaloWill** [comment]
Confirmed.

**Comment by BuffaloWill** [comment]
Landed in https://github.com/SerpicoProject/Serpico/commit/e70ac1b13abc702cd64b8af8f5cef4f4b8fff09a
