### ISSUE TITLE
[Feature Request] Add Editor Role

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#190]
Add Editor role that has the following permissions:

1) Can Edit all reports currently listed
2) Can Add/Remove/Modify findings to the template database
3) Can Add/Modify Templates

**Comment by BuffaloWill** [comment]
This has been discussed before and decided not to implement. 

Do you know about the collaboration for reports? A user (or admin) can add other users to a report.  This would cover 1. Doesn't help with 2 and 3 though.

I'll leave this as an enhancement and we'll vote on the team.

**Comment by aconite33** [comment]
The way we've approached this is, we would have a technically writer apart of our team. He would be the one that would review/edit reports and their findings to make sure their up to snuff. They don't need the full rights as an admin (changing configuration of the server, being able to add users, etc.), but would have enough rights to see all the reports with modify rights.

Another feature which would be useful is the template editing/modifying. Again, I feel that an administrator shouldn't be the only person that can modify/edit a template as with technical writers/editors, they may want to modify how the outlay of the report should look/feel. They don't need admin permissions.

**Comment by Petessss** [comment]
Now that the plugin framework is available this would make a great addition.  If you have any questions or need any assistance let us know.
