### ISSUE TITLE
[Feature Request] Risk Calculator

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#194]
A neat feature would be a risk calculator, so you could assign risk to a finding. If for example, you're using DREAD or CVSS, you could have a side calculator that you could plug in the appropriate risk metrics, and output the score.

Something similar to this: https://nvd.nist.gov/CVSS/v3-calculator

**Comment by BuffaloWill** [comment]
Need to think on this one a bit. The code is there, just about finding a spot for it in the workflow.

**Comment by BuffaloWill** [comment]
This should be added to the plugin project. Easy enough to add. Closing here.

https://github.com/SerpicoProject/SerpicoPlugins
