### ISSUE TITLE
Cancelling an edit on a finding takes you back to the list of reports

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#195]
Workflow: Editing/reviewing findings on a report -> Edit a finding to review the specific details -> Review details, did not modify, hit cancel -> Brings you to the list of reports.

This should return to the previous page, the list of findings in the reports. Instead it brings you to the list of Reports.

**Comment by BuffaloWill** [comment]
Confirmed.

**Comment by BuffaloWill** [comment]
Landed.
