### ISSUE TITLE
HTTPS - CA certificate, chain

### ISSUE THREAD

**Issue by jstangle** [SerpicoProject/Serpico#196]
Hi guys,
It's pretty difficult to solve the small issue around https connection. I have got public key, signed certificate by official CA and all of these are imported to the same directory as previous. However for well working SSL connection I need import CA certificate, its chain. I suppose there was't anyone. Could you give me an advice where to put it please? Is it implemented? Thanks. :)

**Comment by BuffaloWill** [comment]
@jstangle did you get this figured out?

**Comment by jstangle** [comment]
I'm talking about 
"ssl_certificate": "cert.pem",
"ssl_key": "key.pem",
Existed in /opt/Serpico/Serpico

For well working https I need include certificate of CA. Is it possible to add it any way? Or Am I still out?

**Comment by Petessss** [comment]
@jstangle, adding something like this to helpers/sinatra_ssl.rb may fix your issues.
intermediateCert = File.open(intermediate.crt).read
server_options[:SSLExtraChainCert] => OpenSSL::X509::Certificate.new (intermediateCert)

If this does not work let me know.

**Comment by jstangle** [comment]
Thanks. That's it. :)
