### ISSUE TITLE
Add Attachments in Bulk

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#198]
It would be nice to be able to add attachments in bulk.

**Comment by bandrel** [comment]
Or maybe for the second one if the field is blank, just use the file name as the description.

**Comment by BuffaloWill** [comment]
Thanks @bandrel. There are definitely a few updates to make regarding attachments and workflow for image inserts. This is two features. Could you create a second one "Automatically Set File Description Field in Attachment Upload"?
