### ISSUE TITLE
Automatically fill in the "File Description" field for attachments

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#199]
Automatically fill in  the description field for attachments or if the field is left blank, use the filename for the the File Description.

**Comment by BuffaloWill** [comment]
Thanks!

**Comment by BuffaloWill** [comment]
Removed the file description field for now, seems redundant. The name of the file is now inherited, should be a faster workflow.

Landed in https://github.com/SerpicoProject/Serpico/commit/88c80314ae3b5d2b557b96f7a14d59366b5d2407
