### ISSUE TITLE
Add ability for screenshots to be included in presentation

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#200]
The syntax [!! filename.png !!] when added to the presentation data section of the finding does not inject images into the presentation.

**Comment by bandrel** [comment]
I did find a workaround for this safe off the html file and then run sed against the file:

sed -ri 's/\[\!\!\ (\S+) \!\!\]/<img src="\1">/' Example_Report_Presentation.html

There is an annoying bullet next to the image, but then again it's just a workaround.

**Comment by BuffaloWill** [comment]
landed.
