### ISSUE TITLE
Download presentation as PDF

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#201]
Can we generate a Powerpoint presentation using Serpico.
I could generate presentation, but I cant see any option to download it.
Can  you please let me know if there is any such feature??

**Comment by Petessss** [comment]
@shalinich pull request https://github.com/SerpicoProject/Serpico/pull/149 should address this this request.

**Comment by shalinich** [comment]
I am not able to generate any presentation after using pull request 149.It is generating blank screen
Can you please suggest me If there were any other updations

**Comment by BuffaloWill** [comment]
Should be fixed now. Committed in https://github.com/SerpicoProject/Serpico/commit/9f76c18d1b3b88ab587b396fef63852d2ac096c9
