### ISSUE TITLE
Move config.json to config.json.defaults

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#203]
Move config.json to config.json.example and have /opt/Serpico/init_serpico.sh copy the config.json.example to config.json.

This way you can stop tracking config.json within git.  I have an updated config.json file and I am unable to do a git pull without merging the files and correcting the conflicts.

**Comment by Petessss** [comment]
@bandrel thanks for the suggestion. I'll make that update in the next release.

**Comment by BuffaloWill** [comment]
I added a config.json.defaults and  updated the first_time.rb script to perform the copy for the user. So this should take care of creating configuration on first run. config.json is no longer tracked by git also.
