### ISSUE TITLE
Positive Findings

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#204]
Many times in reports we like to include positive findings so that the organization can reflect on the good things that they have been doing.  Would it be possible to add a Positive finding section?

**Comment by Petessss** [comment]
@bandrel, that should be possible by modifying your template and adding a Positive findings section.

**Comment by bandrel** [comment]
Ok.  I understand what you are saying, but I am having trouble with the syntax.  
I want to iterate through the findings where the type is "Positive".  What is wrong with the following syntax?
```
¬report/findings_list/findings:::type=Positive¬
πtitleπ
∆

```

**Comment by BuffaloWill** [comment]
Hey @bandrel, you should be able to do a string comparison to get positive findings as discussed in 

https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report

String comparison should get easier soon, but that's how it is done for now.

**Comment by bandrel** [comment]
Thank you, I can't believe I completely missed that section of the wiki.  Thanks for being prompt with the response
