### ISSUE TITLE
[Feature Request] Finding Enabled/Disabled

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#205]
Would be useful if you were drafting a report and you don't agree if a finding should be included, if you could turn a finding "On/Off" or "Enabled/Disabled". Similar to how you submit a finding to the database, but it hasn't been approved yet.

Use case: Haven't confirmed finding is a false positive yet, but want it in the report so other authors/penetration testers can see the finding and validate if needed.

**Comment by BuffaloWill** [comment]
@aconite33, there is a status setting for findings; confirmed, unconfirmed. This can be used to optionally display findings in a report.
