### ISSUE TITLE
Issues connecting to Metasploit RPC connection

### ISSUE THREAD

**Issue by vipergts46** [SerpicoProject/Serpico#206]
I've tried to start up Metasploit RPC two ways. One from within metasploit using `load msgrpc` and from the cli from root user using `msfrpcd -U $username -P $password -a 127.0.0.1 -p 5432`

I went into Administration > maintenance menu > Modify Configurations and checked vulnmap * auto_import

restarted Serpico
Configured the RPC in Serpico 

When I try to import the DataBase Serpico shows the following
_connection to MSF RPC daemon failed. Make sure you have msfprcd running and the settings in Serpico are correct._   

I see the connections using netstat -nat 

```
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN 
tcp        0      0 127.0.0.1:55552         0.0.0.0:*               LISTEN  
```

**Comment by BuffaloWill** [comment]
@ccammilleri - any troubleshooting steps you would recommend? 

@vipergts46 - were you able to get this working?

**Comment by BuffaloWill** [comment]
Closing this; fixed on IRC. For future reference, Ruby 2.3.x breaks this functionality. Make sure a valid Ruby version is being used.

**Comment by sobergods** [comment]
I'm having this same issue, care to share how it was solved

**Comment by Petessss** [comment]
The command above is missing the -S for SSL.  By default the msfrpc-client has SSL enabled, for obvious security reasons we default to this. If you want to use non-SSL RPC you can modify the helpers/vuln_importer.rb file to disable SSL. Look at the function at line 72. We do not support non-SSL RPC, so, if you make this change your on your own.

**Comment by sobergods** [comment]
@Petessss 
Trust me, msfrpcd -U admin -P password --SSL was used, i only tried to use without SSL since with SSL was giving me error connection to MSF RPC daemon failed. Make sure you have msfprcd running and the settings in Serpico are correct.

My configs are right, i'm using ruby 2.1.5 for both metasploit and Serpico and SSL is turn on, both on Serpico and MSFRPCD
I think I'm doing something wrong since I'm the only one with this issue, i really don't know what

**Comment by ccammilleri** [comment]
@sobergods 
Have you verified you see traffic to and from msfrpcd with tcpdump/wireshark? Do you have a workspace set and is it correct? Please join the IRC again and we can continue tshooting.
