### ISSUE TITLE
Administration and Findings Database were missed in my Serpico GUI

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#209]
I installed the latest version of Serpico from github,and I identified that Adminstration ,Findings database ,admin report templates were missing. 
Please let me know what am I missing

**Comment by BuffaloWill** [comment]
@shalinich, please use the issue template. 

## Describe the issue and steps to reproduce

1. ...
2. ...

**Comment by BuffaloWill** [comment]
Closing, please re-open if this is still an issue. Thanks!
