### ISSUE TITLE
Download presentation in form of PDF

### ISSUE THREAD

**Issue by shalinich** [SerpicoProject/Serpico#212]
Download presentation in the form of PDF
1.Installed latest version of Serpico
2.If I click on generate presentation in pdf option,it is generating blank page
3.Please suggest me if I am missing something

**Comment by BuffaloWill** [comment]
@shalinich what browser and version are you using?

**Comment by BuffaloWill** [comment]
@shalinich please confirm that you have completely updated your instance. This sounds like an older version of JS causing this. Also, you will need to "Print" > "Save as PDF" in your browser to get a PDF copy of the slides.
