### ISSUE TITLE
Unable to clone Repo

### ISSUE THREAD

**Issue by parag85** [SerpicoProject/Serpico#215]
Unable to clone Serpicon Repo to my machine.

Steps:
1. git clone https://github.com/SerpicoProject/Serpico.git

Following error comes:

![serpico](https://cloud.githubusercontent.com/assets/8840359/19065762/f8c32cd6-8a32-11e6-9b3a-3c1d82cbaceb.JPG)

![serpico-1](https://cloud.githubusercontent.com/assets/8840359/19072689/356a989c-8a54-11e6-89b2-90699621b0ac.JPG)

**Comment by Petessss** [comment]
@parag85, In the first screenshot you're pulling from the wrong repo.  Your second error appears to be an SSL issue. Please make sure your version of git and openssl are updated.
