### ISSUE TITLE
missing Affected Url

### ISSUE THREAD

**Issue by daudmalik06** [SerpicoProject/Serpico#217]
Hello 
i generated report everything was okay but was missing Affected Url for all kind of findings
Thanks

**Comment by BuffaloWill** [comment]
Hi @daudmalik06. This sounds like a problem with your report template. 

Please use the required Github Issue template in the future when submitting an issue. Closing.

**Comment by daudmalik06** [comment]
i am using the default template called generic risk scoring ,
i haven't edit or modified that.

**Comment by Petessss** [comment]
@daudmalik06, please use the following template when submitting issues:

# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. ...
2. ...

**Comment by daudmalik06** [comment]
1:I clicked on New Report "https://localhost:8443/report/new"
2:filled basic info names etc and report type options i didn't touch it was pre selected as "default template - generic risk scoring"
3:then i saved it and app redirected me on another page "https://localhost:8443/report/4/edit"
4:i clicked on save and then on "Add finding from tempelates" from there i selected sqli and save
5:then app redirected me to "https://localhost:8443/report/4/findings_add"
6:i clicked on edit button of recently selected sqli and added just random url in "affected Url 2 box and saved
7:then i clicked on generate report
8:it made report everything was fine except the affected url was missing
i am attaching screenshot

![proof](https://cloud.githubusercontent.com/assets/3526480/19234301/04ca063c-8eeb-11e6-8c22-c5345996b67a.JPG)



p.s i am using the serpico on windows 10

**Comment by BuffaloWill** [comment]
@daudmalik06 I can see from the screenshot there is no affected urls section to your template. You will need to have this section in the template or it will not appear in the report. 

Make sure you have downloaded the latest version of Serpico or download the template from 

https://github.com/SerpicoProject/Serpico/blob/master/templates/Serpico%20-%20GenericRiskScoring.docx

Open up the template and make sure the affected urls section is in it.

**Comment by daudmalik06** [comment]
@BuffaloWill  thanks for kind reply,
i have downloaded the latest one and i think it was an executable program which installed the serpico app automatically and yes i can see "affected url" in UI of the app , i had added the url's there but still can't see in report i don't know why.

**Comment by daudmalik06** [comment]
and now i tried to update the template as suggested by you , but still same error
