### ISSUE TITLE
Substitution user defined variables inside a loop.

### ISSUE THREAD

**Issue by jacksonfylle** [SerpicoProject/Serpico#219]
Hello,
## substitution user defined variables inside a loop.

I'am unable to substitute a user variable inside the findings section of the report : 

¬report/findings_list/findings:::risk¬
§my_executive_summary§
∆

Thanks for you're help

**Comment by BuffaloWill** [comment]
Thanks @jacksonfylle but I could not reproduce. Closing for now.
