### ISSUE TITLE
The style of paragraph changed between the report template and the generated report

### ISSUE THREAD

**Issue by QChabert** [SerpicoProject/Serpico#223]
Hi,

I'm using Serpico to generate a report, but I'm having a problem because the style is not kept between the report template and the generated report.
Indeed, for this kind of substitution fields {@overview}, the substitution function only keeps one style of paragraph where the {@overview} markup is present. 
I explain : I'm supposed to have one overview paragraph in font-size 8 and another one in font-size 11. But as a result of the generated report, both paragraphes have the same font-size. That is annoying because I need to change it manually for each finding. 

Does someone have the same problem or already solved it ?
If someone could help me I'd be really thanksful.

EDIT : I tried a global substitution of w:val=16 into w:val=22, in xslt_generation.rb in initialize method around line 90, but this substitution is also applied to the paragraph where I'm supposed to have a font-size of 8 (or 16 for xslt). Anyone an idea ?

Cheers

**Comment by BuffaloWill** [comment]
Hi @QChabert. It's best to use Word styles rather than fonts. Could you please re-try the same process but with multiple styles applied in the template? This solves the issue in most cases.

**Comment by QChabert** [comment]
Hi @BuffaloWill , thanks for the answer. I applied one style "size8InArray" and another one "normalStyle" to the different paragraphs in the template, but still the same problem when generating the report, normalStyle paragraph becomes of style size8InArray.

So I think I will just manually change the size of the content of this array column finally.

Thanks for this great tool by the way ;)

**Comment by BuffaloWill** [comment]
Ok, sounds good.
