### ISSUE TITLE
MSFPRCD connection Issue

### ISSUE THREAD

**Issue by sobergods** [SerpicoProject/Serpico#227]
I'm running Serpico with ruby 2.3.3, i can't connect to MSFPRCD, i get this error 
ERROR: Connection to metasploit failed. Make sure you have msfprcd running and the settings in Serpico are correct.

**Comment by ccammilleri** [comment]
@sobergods you might have a connection issue to your msfrpc daemon, or your settings are incorrect, or you have not started the daemon. Without more relevant information, I can't provide much assistance. 

Serpico supports ruby 2.1.5. However, I doubt this is related to your issue, but its best to use the supported ruby version.
