### ISSUE TITLE
MSF RPC connction issue

### ISSUE THREAD

**Issue by sobergods** [SerpicoProject/Serpico#228]
I recently opened an Issue about this but then i changed ruby to 2.1.5 and i'm still unable to connect to MSF RPC , I get this error connection to MSF RPC deamon failed. Make sure you have msfprcd running and the settings in Serpico are correct.

the configs are right and MSFRPCD is up and listening on 55553, when MSF RPC is configured with SSL turned off, it never connect but with SSL 
Anyone who got this working on Kali should please assist

**Comment by Petessss** [comment]
@sobergods 
 By default the msfrpc-client has SSL enabled, for obvious security reasons we default to this.  If you want to use non-SSL RPC  you can modify the helpers/vuln_importer.rb file to disable SSL. Look at the function at line 72.  We do not support non-SSL RPC, so,  if you make this change  your on your own.
