### ISSUE TITLE
Risk as color in markup

### ISSUE THREAD

**Issue by aoighost** [SerpicoProject/Serpico#230]
Having the ability to generate the risk as a color in a column in a table in markup would be very helpful for some reporting templates. If I could get some information on what exactly is being used to generate the docx files and the mechanisms involved, I could probably implement myself and pull request.

**Comment by BuffaloWill** [comment]
@aoighost this is possible. I would suggest taking a look https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth

Also, have a look at the templates provided in the project; https://github.com/SerpicoProject/Serpico/tree/master/templates. There are examples of colors places into tables depending on risk (e.g. critical finding).
