### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Dissonia** [SerpicoProject/Serpico#235]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Trying to run Serpico for the first time - ruby first_time.rb
Bundles correctly installed - Ubuntu 16.04

## Feature Request

running command - ruby first_time.rb 

### Example Use Case

/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ./model/master.rb (LoadError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from first_time.rb:1:in `<main>'

**Comment by Petessss** [comment]
1) How did you install Serpico? Did you pull it from git or use the installer
2) Did you run "ruby scripts/first_time.rb"? You need to make sure you are in the right directory. 
3) Ruby 2.3 is not supported at this time.

**Comment by Dissonia** [comment]
Thanks for the quick response.

1 - Used the git clone method then proceeded with bundle install > install necessary dependencies so everything install successfully.

2 - yes im in the correct directory which is in the following path Serpico/scripts/ruby first_time.rb
3 - I guess I'll have to downgrade to 2.2? or which version is preferable?

Thanks for the help.

**Comment by Petessss** [comment]
You need to run the script from the root Serpico directory. Example:  ruby scripts/first_time.rb.  

Ruby 2.1.5 is the current version we support.

**Comment by BuffaloWill** [comment]
Closing, please re-open if unresolved. Thanks!

**Comment by Dissonia** [comment]
Hi there,

Sorry for getting back only now.

Yes I have managed to resolve the issue, seems to be working fine on ruby 2.3
