### ISSUE TITLE
Overall Report Type

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#239]
## Feature Request

Is it possible to define an overall report type example Web Application or Network, mobile or Hybrid. Instead of creating seperate templates for each type i would love to have an option where i can use variables to decide what type of report it is and based on that my template could be Worked on using if else conditions.

-Anant

**Comment by BuffaloWill** [comment]
@anantshri Could you give an example work flow?

**Comment by anantshri** [comment]
One simple example is if the final report is more or less the same except for few simple sections i would prefer maintaining one reporting template with internal if else blocks based on report type. Right now we have issue types at each issue level  its network  / web / mobile  etc. I would prefer a overall report type if the report is Network or Mobile or Web.

Maintaining consistency across multiple word documents vs managing a single document: single document wins hand's down.

So user creates a report selects a report type instead of picking specific templates and based on the report type the template has if else allowing sections to be picked or dropped from the final report.

Does this makes sense.

**Comment by BuffaloWill** [comment]
Ah, this makes sense. Great idea. Discussing internally now, but here is what I am thinking:

1. add a new column in the DB for assessment_type in the Report model
2. update the view to allow users to select the assessment type
3. you could then update your templates to do a string comparison on assessment_type for the optional sections within your template.

**Comment by ITGSean** [comment]
Excellent idea!  This would make template maintenance a LOT easier!  (Currently maintaining 4 templates and counting)

**Comment by BuffaloWill** [comment]
This just landed in PR307. Hopefully makes life a lot easier in terms of only have to maintain one template.
