### ISSUE TITLE
Pre set values for UDV (User defined Variable)

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#240]
## Feature Request

Is it possible to have pre-set values in say a drop down for User Defined Values. this could help me in setting some pre defined question answer for consultants to fill in and based on that some template formatting and actions could be performed.

**Comment by BuffaloWill** [comment]
@anantshri I wrote a plugin that partially implements this functionality. Minding providing more information after testing it out? It's beta so I wouldn't test it out on your prod instance yet. 

Plugin : https://github.com/SerpicoProject/SerpicoPlugins/tree/master/UDV_Worksheet

Blog Post: https://www.serpicoproject.com/blog/2016/12/17/udv-worksheet-example/

**Comment by anantshri** [comment]
@BuffaloWill tried this today but seems like whenever i click on Go to Administrator Specific Plugins (https://IP:8443/admin/admin_plugins) > UDV_Worksheet i get a "Sorry, I don't know this page." Will dig deep later.

**Comment by BuffaloWill** [comment]
@anantshri did you restart? Unfortunately you have to restart or the plugin won't be loaded.

**Comment by anantshri** [comment]
Tried restarting a bunch of time for good measures restarted the whole box also but still same error message.

**Comment by BuffaloWill** [comment]
@anantshri closing this issue for now. please re-open if it's still not working for you
