### ISSUE TITLE
Drop-down menu and text fields for risk context

### ISSUE THREAD

**Issue by infosecrepo** [SerpicoProject/Serpico#244]
Feature request:

The ability to add additional context and a qualifier for Impact and Likelihood for generic risk ratings.

-Drop down menus for Impact and Likelihood (Low-High) variables that can be inserted into the generated report.

-Two additional text fields for Impact and Likelihood analysis descriptions.

**Comment by BuffaloWill** [comment]
Going to close this.

Should be covered by RiskMatrix scoring (https://github.com/SerpicoProject/Serpico/pull/152) or CVSS.
