### ISSUE TITLE
Counting findings  based on rating

### ISSUE THREAD

**Issue by Dionka** [SerpicoProject/Serpico#245]
**Feature Request**

I would like to add a paragraph at my report for the executive summary like this one:
We identified 10 vulnerabilities. These vulnerabilities are distributed as follows:
1 vulnerability associated to a high risk
3 vulnerabilities associated to a medium risk 
6 vulnerabilities associated to a low risk

How can I do that?? How can I count total findings as well as findings based on rating as well?

**Comment by Petessss** [comment]
Appears to be the same request as #246. Closing and working off of #246.

**Comment by Petessss** [comment]
Reopened. Not the same as#246.

**Comment by Petessss** [comment]
I'm checking to see if this can be done with UDVs and a plugin.

**Comment by Petessss** [comment]
@Dionka you can try using the plugin framework with global user defined variables to accomplish this.  

Setup global UDV variable for each risk level. Example: severe_number, critical_number
(https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Variables)

Next create a plugin (https://github.com/SerpicoProject/SerpicoPlugins/wiki). It could have code something like this:

  @findings.each do |finding|
                    if finding.risk == 4
                      vulns["critical"] += 1
                    elsif finding.risk == 3
                      vulns["severe"] += 1
                    elsif finding.risk == 2
                      vulns["moderate"] += 1
                    else finding.risk == 1
                      vulns["low"] += 1
                    end

Then update the Global UDV with the values:
@findings.user_defined_variables["severe_number"] = vulns["severe"]
@findings.user_defined_variables["critical_number"] = vulns["critical"]

Then in the report template add the following to get the totals. 
The number of critical vulnerabilities are: §critical_number§ 
The number of severe vulnerabilities are : §severe_number§

**Comment by Dionka** [comment]
Thank you thank you thank you very much. I will try it now and let you
know! Thank you very much for the support! Really appeciate it!

Στις 12 Ιαν 2017 20:36, ο χρήστης "Peter" <notifications@github.com> έγραψε:

**Comment by Dionka** [comment]
2017-01-12 21:48 GMT+02:00 Dionisia Lerataki <dionisialerataki@gmail.com>:

**Comment by Petessss** [comment]
@Dionka if this does not work for ya, please reopen.

**Comment by pentestgou1** [comment]
Did someone already make a fix / plugin for this issue?

**Comment by Dionka** [comment]
Hi,
When I attempted it, I didnt manage to make it work.
However, i noticed that it already counds findings in dashboard. Maybe
there is a workaround to use this counting somehow?

Στις 18 Απρ 2017 16:29, ο χρήστης "pentestgou1" <notifications@github.com>
έγραψε:
