### ISSUE TITLE
Adding New 'Assessment Type' to New Findings

### ISSUE THREAD

**Issue by scottdwallace** [SerpicoProject/Serpico#247]
Hello - Loving Serpico! Just have a quick question. When going to 'List Reports' > (Edit Report) > 'Create New Finding', we come to a page with one option of 'Assessment Type' where one can choose External, Internal, etc. Is there a way through the web interface to edit this or does it have to be manually added to the database? 
Thank you!

**Comment by Petessss** [comment]
You'll have to add a new report temple for that Assessment Type. 
Login as an Admin
From ADMIN REPORT TEMPLATE MENU select Add Report Template. 
Set the Report Type to the new type of report 
Upload your new template and save
 
The next time you create a report you'll see the new report type listed.
