### ISSUE TITLE
Affected Hosts/URLs using bullets & numbering

### ISSUE THREAD

**Issue by habibiefaried** [SerpicoProject/Serpico#250]
# I think it should be better if we can format the Affected Hosts section minimum with bullets and numbering word standard
-------------------
## Bug
Describe the issue and steps to reproduce

1. Add findings
2. Write the Affected Host
3. Input example string `*- Bulleted text goes here -*`
4. No bullets shown on word generated document

**Comment by BuffaloWill** [comment]
@habibiefaried have you tried using a for loop similar to the overview paragraph?
```
¬affected_hosts/paragraph¬ 
µCONDITIONALµ π.π
ƒbulletƒ π.π
÷ π.π ≠
```

**Comment by habibiefaried** [comment]
Hi sorry I just read this.

I'll try it.
Thanks mate!
