### ISSUE TITLE
Multi-language report

### ISSUE THREAD

**Issue by Demaz93** [SerpicoProject/Serpico#253]
## Feature Request

It could be awesome have the possibility to manage multi language report.
Findings in multiple language (SQL_Injection_EN, SQL_Injcetion_ES, etc..)

### Example Use Case

During the creation of a new report, whit information about customer we can choose the language of the report. If I choose EN I can choose only english findings.

**Comment by martindube** [comment]
Hi BuffaloWill,

Our team also need multi-language support. If you agree, do you have any guidelines for such a change? 

Thanks,

**Comment by nate-fr** [comment]
@BuffaloWill Is someone working on this?
We need this for our team.

**Comment by BuffaloWill** [comment]
Hi @Demaz93. I just pushed this feature. I also added a wiki page with a usage example: https://github.com/SerpicoProject/Serpico/wiki/Multi-Language-Usage.

Please let me know if you have an feedback or create an issue if something is not working correctly.

cc: @nate-fr @martindube
