### ISSUE TITLE
Nmap scan inport

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#256]
## Feature Request

Ability to import nmap host scans from a scan like "nmap -sV"

### Example Use Case

It would be awesome to be able to import nmap scans so Serpico could output:

IP  
Port  Protocol  State(closed/open)  Service(http/ldap/ftp etc)  VersionDetected(apache etc)

**Comment by Petessss** [comment]
We recommend using the Metasploit connector for this. 
https://github.com/SerpicoProject/Serpico/wiki/Setting-up-Metasploit-RPC-Connection
