### ISSUE TITLE
RPC connection Metasploit Pro

### ISSUE THREAD

**Issue by Vincent1233** [SerpicoProject/Serpico#258]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. Start up Metasploit pro : /opt/metasploit/msfpro 
2. Launch rpc on metasploit pro

[+] Metasploit Pro extensions have been activated
[*] Successfully loaded plugin: pro

msf-pro > load msgrpc
[*] MSGRPC Service:  127.0.0.1:55552 
[*] MSGRPC Username: msf
[*] MSGRPC Password: abc 
[*] Successfully loaded plugin: msgrpc
https://help.rapid7.com/metasploit/Content/framework/msf-rpc-service.html

3. Seprico RPC connection 

 Specify the metasploit RPC settings for this report.
IP Address :127.0.0.1
Port : 55552 
Username : msf
Password : abc 
Workspace : default   (Or empty or one of the DB's in metasploit like Beebox1 doesn't work)

4. No error but infinite loading when pressing on Host of Vulnerabilites under Serpico Metasploit Data Management

Note : when using msfrpcd -U $username -P $password --ssl everything works, but than i dont with the metasploit pro functionality.

**Comment by pentestgou1** [comment]
My mistake, i just found out this (msgrpc) is a know issue. 
Msfrpcd does work when given the correct Workspace name  (equal to the database name in the Metasploit browser). 
 
https://github.com/SerpicoProject/Serpico/wiki/Setting-up-Metasploit-RPC-Connection
- Do not use "load msgrpc" within msfconsole, instead launch via the command line tool msfrpcd.

**Comment by Vincent1233** [comment]
Still one problem. Vulnerabilities from Metasploit are shown, but not imported. 
When using the "Auto Add Vulnerabilities from Metasploit DB" option

![1 metasploit findings visable](https://cloud.githubusercontent.com/assets/3727682/25129417/40850d8c-243e-11e7-897f-63987567454b.png)
![2 import findings from metasploit db](https://cloud.githubusercontent.com/assets/3727682/25129419/4085a9e0-243e-11e7-9623-529181c1d820.png)
![3 no findings](https://cloud.githubusercontent.com/assets/3727682/25129418/4085c36c-243e-11e7-8c5d-ab807bc9dcfe.png)

**Comment by Petessss** [comment]
Did you setup your vulnerability maps?  Check out https://github.com/SerpicoProject/Serpico/wiki/Setting-up-Metasploit-RPC-Connection

**Comment by Vincent1233** [comment]
Yes i did, and a restarted my VM (I didn't find a better way to have a clean restart?)
![4 config](https://cloud.githubusercontent.com/assets/3727682/25130051/0a22f4a4-2441-11e7-93ca-882c56aac329.png)
I can for example open the Nessus import console without Error message. 
![5 nessus import](https://cloud.githubusercontent.com/assets/3727682/25130224/baff1780-2441-11e7-8a9c-33b0a931bc75.png)

**Comment by Petessss** [comment]
I'm referring to this part: "Each Serpico finding you want automatically mapped will have to have a CVE (or other supported ID) assigned to the finding. This is done by editing the finding in the findings database. More information on what IDs are supported can be found by clicking on the "Add new vuln mapping ID" button". If you dont have the CVE or supported ID's map to a finding the auto mapping will not work.

**Comment by Vincent1233** [comment]
Thanks you, that was indeed the problem.  However i can import Nessus files without CVE/ID mapping. Is this not possbile for the metasploit BD?
