### ISSUE TITLE
UDV_Worksheet : Crash when saving twice  

### ISSUE THREAD

**Issue by pentestgou1** [SerpicoProject/Serpico#259]
Serpico crashes when saving the  variables in the UDV_Worksheet twice.

- No saving =  everything oke 
![1 udv_worksheet](https://cloud.githubusercontent.com/assets/27432586/25178457/30bfcf0e-2506-11e7-9ccb-c8ba390df884.png)

- Saving once =  everything oke 
![2 udv_worksheet save once](https://cloud.githubusercontent.com/assets/27432586/25178458/30bfee76-2506-11e7-8dcd-8943e8f3e99e.png)

- Saving twice =  error / crash 
![3 udv_worksheet save twice](https://cloud.githubusercontent.com/assets/27432586/25178459/30c066c6-2506-11e7-90f6-0ded043a96e6.png)

**Comment by Petessss** [comment]
hmm the url is incorrect in your last image. Its missing the 1 after the report_id. When you say crash, is the system unusable or you just receive the No Such Report?

**Comment by pentestgou1** [comment]
It just says No Such Report.  When going pressing back a second error appears. When pressing back again the menu shows in its pre saved stated (fields emty/default value)

**Comment by Petessss** [comment]
Ok. I'll have to spin up a test instance and see if I can reproduce it.
