### ISSUE TITLE
Line break in User Defined Variables (Meta Language)

### ISSUE THREAD

**Issue by pentestgou1** [SerpicoProject/Serpico#260]
Is is possible to have a User defined Variable with line break.

Example

Variable  §Team_members§   =  Team member 1
                                                   Team member 2

Output is   = Team member 1 Team member 2

Desired output  = Team member 1 
                             Team member 2
(line break between 2 value's in the same variable string)

**Comment by BuffaloWill** [comment]
Hi @pentestgou1 

Yes, you can apply formatting to a UDV similar to a finding. For example, say my UDV is team_members:

```
¬report/udv¬
¬team_members/paragraph¬ 
π.π
∆
```

**Comment by BuffaloWill** [comment]
Updated the wiki:

https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth

**Comment by pentestgou1** [comment]
Thnks for the solution. I still have to problem : 

When using : 

**List of users 1 :**
¬report/udv¬
¬team_members/paragraph¬ 
π.π
∆

**List of users 2 :**
¬report/udv¬
¬team_members2/paragraph¬ 
π.π
∆

With both team_members and team_members2 consisting of    
Jan1 Jansen1
Jan2 Jansen2

**Problem1:** Only the first loop is shown.
**Problem2 :** The output has many white lines between lines. 

Given out: 

_emtpy
emtpy_
Piet1 Jansen1
_emtpy
emtpy_
Piet2 Jansen2
_emtpy
emtpy_
_(No second look / users2)_

Desired output 

Piet1 Jansen1
Piet2 Jansen2

Piet1 Jansen1
Piet2 Jansen2
(No Enters and a second loop.)
