### ISSUE TITLE
Ability to use variables in headers/footers

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#261]
## Feature Request

Use Serpico variables in headers and footers

### Example Use Case

Often a report needs the client name & name of text in the headers and/or footers.  Currently serpico doesn't replace the variable name with the correct text.

**Comment by BuffaloWill** [comment]
@ITGSean thanks. 

Developer notes:
- Header and footer are stored in word/header*, word/footer*
- Can use docx_modify(rand_file,docx_xml,'word/header1.xml'), etc to insert
- Should limit to variables only

**Comment by ITGSean** [comment]
Could you expand on the above text please?  It isn't very clear what you mean.

Thanks

**Comment by BuffaloWill** [comment]
The developer notes are for tracking how to implement the enhancement.

**Comment by ITGSean** [comment]
Oh OK.  Thanks Will

**Comment by BuffaloWill** [comment]
Landed in https://github.com/SerpicoProject/Serpico/pull/323 🍾 👍

**Comment by BuffaloWill** [comment]
Here is the info in the wiki:

https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth
