### ISSUE TITLE
Meta Language : (undisired) Line breaks when using UDV variables (lists).

### ISSUE THREAD

**Issue by pentestgou1** [SerpicoProject/Serpico#263]
Problem when using multiple lines in variables.

Example  :

List of users 1 :
¬report/udv¬
¬team_members/paragraph¬
π.π
∆

List of users 2 :
¬report/udv¬
¬team_members2/paragraph¬
π.π
∆

With both team_members and team_members2 consisting of
Jan1 Jansen1
Jan2 Jansen2

Problem1: Only the first loop is shown.
Problem2 : The output has many white lines between lines.

Given out:

emtpy
emtpy
Piet1 Jansen1
emtpy
emtpy
Piet2 Jansen2
emtpy
emtpy
(No second look / users2)

Desired output

Piet1 Jansen1
Piet2 Jansen2

Piet1 Jansen1
Piet2 Jansen2
(No Enters and a second loop.)

**Comment by BuffaloWill** [comment]
Please use the Github issue template. 

There is an issue with the markup in your report template.

**Comment by TKSS3** [comment]
If you use this:
¬report/udv¬
¬team_members/paragraph¬ 
π.π
∆
inside a table, it will corrupt the document
