### ISSUE TITLE
(Multi-language)  change variables

### ISSUE THREAD

**Issue by pentestgou1** [SerpicoProject/Serpico#264]
Is there a good way to rename variables?

Example : Change the effort option Involved to very_involved

Grep: 
/opt/Serpico/Serpico/server.rb:    set :effort, ["Quick","Planned","Involved"]
/opt/Serpico/Serpico/views/create_finding.haml:            %option INVOLVED

Can i just rename Involved and INVOLVED ? 

In config.json there seems to be a better way for finding_types, where a list can editted as config

 "finding_types": [
    "Web Application",
    "Business Logic",
...

**Comment by BuffaloWill** [comment]
Please use the Github issue template. 

Renaming variables is not supported. You could change the effort option in the report via string comparison. However, a plug-in will likely be easier to support and cleaner for your users.
