### ISSUE TITLE
Add testing to/from dates to report information

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#265]
## Feature Request

Most PT reports require the time window of testing to be specified

### Example Use Case

When creating a new report, have extra fields where the consultant can add the from/to dates of the test & include these in the auto-generated report.

I.E:  Testing took place between <start_date> and <end_date>

Thanks,

Sean

**Comment by BuffaloWill** [comment]
Thanks @ITGSean.

If you need this functionality now, you can use User Defined Variables and the UDV Worksheet plugin (https://www.serpicoproject.com/blog/2016/12/17/udv-worksheet-example/).

However, every assessment has a start date and an end date. I will add this in an enhancement. It should be in by default.

**Comment by BuffaloWill** [comment]
Landed.

**Comment by ITGSean** [comment]
Hi @BuffaloWill 

How is this inserted into a report template document?

Thanks,

Sean

**Comment by BuffaloWill** [comment]
@ITGSean use the variables assessment_start_date and assessment_end_date
