### ISSUE TITLE
Generate a table of db_nmap port scan

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#267]
## Feature Request

Despite looking everywhere I can think of I can't see any reference to any template codes which would enable me to get Serpico to generate a list/table of port scan results from hosts imported via MSFRPC.

### Example Use Case

What I need to do is generate a table with the following headings (from running db_nmap <range> -sSV in MSF):

IP_address   Port   State  Service   Version
0.0.0.0          22     Open  SSH        6.1
1.1.1.1          80     Open  HTTP      Apache version x
etc. etc.

The ability to do this would make this reporting tool absolutely invaluable!  If I'm missing existing functionality to do this, could you point me in the right direction please?

Keep up the excellent work!

Thanks,

Sean

**Comment by Petessss** [comment]
I would recommend checking out the plugin framework for this. https://github.com/SerpicoProject/SerpicoPlugins
