### ISSUE TITLE
Multiple References Only Print First Reference

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#270]
## Bug
Describe the issue and steps to reproduce

1. Create a new finding
2. In the reference section, add multiple references, each on their own line.
3. Generate a report
4. Verify that the references are only showing the first reference in a list of references.

**Comment by BuffaloWill** [comment]
Hi @aconite33! 

I haven't tested but this is likely an issue with the template. Can you try adding a for loop into your template references section? If not, I can test within the next 72 hours.

**Comment by MOBergeron** [comment]
You can go with this in your template : 
`¬references/paragraph¬`
`π.π `
`∆`

It will print each paragraph of your references (if they are separated by a new line)

**Comment by BuffaloWill** [comment]
Thanks @MOBergeron!
