### ISSUE TITLE
issues not appearing with correct rating in dashboard nor report after switching scoring modes

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#275]
## Bug
Describe the issue and steps to reproduce

1. I have findings defined in the database as CVSS2, with CVSS3 vectors as "not defined", they are listed in "current findings" in the report and the findings database with a CVSS score of 10.0
2. In the current report findings page, the graph at the top shows totals of zero for critical and high findings, but shows correct totals for mediums and below.  All findings are marked as "approved".

What should I be checking to make the findings score appropriately?

Thanks,

Sean

UPDATE:

This is a bit strange.  I think it's caused by some of the findings initially being created whilst in the default scoring mode, then new ones added when serpico had been changed to CVSS mode.  The new findings were obviously added using the CVSS scoring system.  Try as I might, I could not get them to appear correctly in the report in this mode.  By switching back to default scoring mode, then changing the CVSS 10.0's etc to the appropriate level (critical in this case, obviously), and saving them - THEN switching back to CVSS mode, everything appeared in the dashboard and the report properly.  There's a bug in there somewhere, but I'll be darned if I could give you any pointers as to where it is! :)

**Comment by Petessss** [comment]
We are in the process of updating the scoring code. Once we are done, we'll check this out.

**Comment by Petessss** [comment]
@ITGSean we have pushed the updates to master. Can you please pull the latest code and test? 

Thanks,
Petessss

**Comment by ITGSean** [comment]
seems ok guys at first glance.  will update if I see anything odd
