### ISSUE TITLE
CVSSv2 in new commit cannot be saved as a Risk Scoring Algorithm

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#277]
## Bug
Describe the issue and steps to reproduce

1. In the new commit with CVSSv3 included, you cannot select CVSSv2 in Configuration Options- when the Save button is pressed, Risk Scoring Algorithm reverts to Default.

It appears that you can force the selection by editing config.json - so it appears that something is wrong with the code which saves back to the config file.

**Comment by BuffaloWill** [comment]
Thanks @ITGSean! I just pushed a fix for this. Please let me know if it is working for you.

**Comment by ITGSean** [comment]
Seems to be ok now. Thanks @BuffaloWill
