### ISSUE TITLE
Json + DM-serializer gem dependency conflicts in Ruby 2.4.1

### ISSUE THREAD

**Issue by arnoldmarunda** [SerpicoProject/Serpico#285]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. ...I have Ruby 2.4.1 which has json 2.1.0 gem installed by default. Serpico requires json -v '1.8.3' or lower for dm-serializer-1.2.2. There is a conflict on "bundle install"

is it possible to 'bump' up the json/dm-serializer dependency versions

**Comment by BuffaloWill** [comment]
Hi! Right now we only support Ruby 2.1.5. Any gem conflicts outside of this version are not supported.

Please follow the dev build instructions for working with 2.1.5:
https://github.com/SerpicoProject/Serpico/wiki/Developer-Build

Cheers!
