### ISSUE TITLE
Feature request:  CVSS vectors in short format (not whole word format)

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#289]
## Feature Request

For reporting brevity purposes, it would be handy to have the cvssv2 vectors as letters (in the report, not the Sepico UI) i.e:

AV:N/AC:L/Au:N/C:P/I:N/A:N

..rather than AV:Network/AC:Low etc

Thanks

Sean.

**Comment by BuffaloWill** [comment]
Great idea.

**Comment by BuffaloWill** [comment]
Just landed this feature. You can now use c2_vs and c3_vs to get the CVSSv2 and CVSSv3 vector strings respectively.  

I also added the notes into the wiki:
https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth


Warning, you will need to re-save any existing findings to have the vector string added.

**Comment by ITGSean** [comment]
@BuffaloWill What are the usage guidelines for this? I've resaved a finding and the CVSS vector string isn't being populated.  I was hoping that this would be the case either when I configure the relevant CVSS vectors, it would calculate the string AND/OR if I added the CVSS vector string, the AV/AC/A etc fields would be adjusted accordingly.

Currently, neither happens (from a git pull from 10-hours-old repo).  If I paste in a CVSSv2 vector, the corresponding fields don't change, and if I change the fields, the vector string isn't appearing.

Advice would be appreciated.

Thanks,

Sean

**Comment by BuffaloWill** [comment]
I just pushed a fix for this. My guess is a case sensitivity issue, if you were using "Au" then the field would be ignored. Either way, this should be fixed now if you could re-test. 

Also, if you click on the blue "CVSS Vector String" button, Serpico will help prep the vector string and update the dropdowns.

**Comment by ITGSean** [comment]
My bad on the text case thing - I was copying the vectors straight out of the Nessus UI and into Serpico.  The Nesuss string has lowercase - "Au".

I'm liking the CVSS calc! :+1: 

This is a fantastic improvement to the whole thing!.  Confirmed that the fix is working on my install.

Cheers :1st_place_medal:
