### ISSUE TITLE
[Feature Request]Vector String and Severity Fields for CVSSv2 and CVSSv3

### ISSUE THREAD

**Issue by r3b00t5** [SerpicoProject/Serpico#295]
Feature Request
It would be great to be able to calculate the Vector String based on the vector calculation of a finding and the severity based on the cvss_total field.

CVSS V3 Ratings
1.Vulnerabilities are labeled "Low" severity if they have a CVSS base score of 0.0-3.9.
2.Vulnerabilities will be labeled "Medium" severity if they have a base CVSS score of 4.0-6.9.
3.Vulnerabilities will be labeled "High" severity if they have a CVSS base score of 7.0-8.9.
4.Vulnerabilities will be labeled "Critical" severity if they have a CVSS base score of 9.0-10.0.

CVSS V2 Ratings
Vulnerabilities are labeled "Low" severity if they have a CVSS base score of 0.0-3.9.
Vulnerabilities will be labeled "Medium" severity if they have a base CVSS score of 4.0-6.9.
Vulnerabilities will be labeled "High" severity if they have a CVSS base score of 7.0-10.0.

CVSSv3 Vector String
CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N

CVSSv2 Vector String
AV:N/AC:L/Au:S/C:P/I:P/A:N

References:
https://nvd.nist.gov/vuln-metrics/cvss

**Comment by Petessss** [comment]
Version 3 is already supported. Version 2 request is being tracked via https://github.com/SerpicoProject/Serpico/issues/289

**Comment by r3b00t5** [comment]
I know this is closed, but how do I get the Vector String and Severity rating for CVSSv3?
