### ISSUE TITLE
Auto-Generate Severity Findings Total UDV 

### ISSUE THREAD

**Issue by BuffaloWill** [SerpicoProject/Serpico#299]
## Feature Request

Many report templates use a finding by severity total (e.g. 6 critical findings). Unfortunately this is not trivial to add without a plugin.  When the user clicks Generate Report this feature would sum the findings by severity and create a UDV. 

### Example Use Case

As a user I would like my report template to include a findings by severity as a UDV.

**Comment by ITGSean** [comment]
This is an excellent idea!  Very useful for the exec summary.

**Comment by BuffaloWill** [comment]
Added the feature, details are in the Wiki

https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Variables
