### ISSUE TITLE
dev install errors on bundle install

### ISSUE THREAD

**Issue by ccammilleri** [SerpicoProject/Serpico#301]
-------------------
## Bug
Exiting error on bundle install prevents successful installation.

1. on ubuntu 16.04, follow the dev install instructions
2. during `bundle install` the following error is presented:
```
Downloading msfrpc-client-1.0.3 revealed dependencies not in the API or the lockfile (msgpack (>= 0.5.8, ~> 0.5.8)).
Either installing with `--full-index` or running `bundle update msfrpc-client` should fix the problem.
```

### Example Use Case

"As a developer the dev install from source should work cleanly."

## workaround

I was able to drop the msgpack ver down to 0.5.8 in the Gemfile and Gemfile.lock. Then run `bundle update msfrpc-client` to have it successfully install.

probably should look into supporting msfrpc-client 1.1.0 if we can...

**Comment by ccammilleri** [comment]
my diff
```
iff --git a/Gemfile b/Gemfile
index 046f13a..5838efc 100644
--- a/Gemfile
+++ b/Gemfile
@@ -11,7 +11,7 @@ gem 'nokogiri'
 gem 'do_sqlite3', '0.10.17'
 gem 'data_mapper', '1.2.0'
 gem 'dm-sqlite-adapter', '1.2.0'
-gem 'msgpack', '0.6.2'
+gem 'msgpack', '0.5.8'
 gem 'msfrpc-client', '1.0.3'
 
 
diff --git a/Gemfile.lock b/Gemfile.lock
index 2ee5453..10162fe 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -62,8 +62,8 @@ GEM
     mini_portile (0.6.2)
     msfrpc-client (1.0.3)
       librex (~> 0.0.70, >= 0.0.70)
-      msgpack (~> 0.6.2, >= 0.6.2)
-    msgpack (0.6.2)
+      msgpack (~> 0.5.8, >= 0.5.8)
+    msgpack (0.5.8)
     multi_json (1.11.2)
     net-ldap (0.11)
```

**Comment by Petessss** [comment]
+1 for up'ing msfrpc-client. Will and I were talking about rewriting the msf stuff as a plugin and just parse the xml file. This way we don't have to deal with the msfrpc-client and msgpack dependencies anymore.

**Comment by Petessss** [comment]
Looks like msfrpc-client 1.1.0 requires rex 2.0.10 which requires ruby => 2.2.0. At this point it may be best to move msgpack back to (~> 0.5.8, >= 0.5.8)

**Comment by Petessss** [comment]
removing msgpack from the gem file looks like a good short term fix.

**Comment by Petessss** [comment]
https://github.com/SerpicoProject/Serpico/pull/302 please test.

**Comment by BuffaloWill** [comment]
Landed 302, closing until further notice.

**Comment by ccammilleri** [comment]
this error has started up again.

looks like msgpack is now defaulting to 0.6.2. maybe due to gem lock having 0.6.2 specified.

making changes from the original diff fixes it.

...as i write this i hear 2.3 is in the works and that will allow msfrpc-client to be upgrading fixing this issue. closing issue.
