### ISSUE TITLE
Question: Best way to upgrade Serpico dev release

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#304]
Excuse what probably is a stupid question, but what is the best (and easiest) non-destructive way to upgrade Serpico from a git clone of the dev release? My mind has gone blank!

Historically, I've been git cloning to a fresh folder and restoring the findings DB from the last worked-on version.

Is there a way of using git so that it just upgrades the bug-fixed (or improved) files and preserves files like master.db?

Thanks

Sean

**Comment by BuffaloWill** [comment]
Hi @ITGSean. master.db should never be modified by the origin/master project. It is not tracked by the project. You are safe running 'git pull' in your existing project. That being said, make sure to regularly run backups (Administration > Backup Master Database/Backup All Attachments). Also, make sure to backup your templates regularly.

To answer the question, regularly create backups and store them elsewhere. Run 'git pull' within your existing installation to upgrade the version.

**Comment by ITGSean** [comment]
Hi Will - thanks - just wanted to make sure!  Sean
