### ISSUE TITLE
Adding a user to report

### ISSUE THREAD

**Issue by aconite33** [SerpicoProject/Serpico#305]
## Feature Request

1) Create report
2) Add Collaborator to report
3) Get redirected back to list of reports

Describe the feature and give an example use case

### Example Use Case

Instead of being redirected back to list of reports, reload page of revised list of collaborators on report.

#### Issue

Requires multiple click throughs to add users to report. Can be cumbersome when you have multiple operators/editors for reports.

**Comment by BuffaloWill** [comment]
Thanks for the detailed finding request @aconite33. I just landed this.
