### ISSUE TITLE
Feature request:  Critical rating switch for CVSSv2

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#309]
Copied from the conversation with @BuffaloWill : 

> Hey Sean.
> 
> Aah - Just realised that the "official" CVSSv2 line is that there are no Critical-risk mappings to the score
> This is correct. I /almost/ broke away from the official scoring because I think it's silly not to have a critical level finding. But it wouldn't match the critical_tally UDV as discussed below.
> 
> Could the option to switch criticals on in CVSSv2 be added?
> Could you submit a feature request? One unfortunate draw back is the UDV tallies will be different. For example, the graph will show the critical total as N but the UDV critical_tally will always be 0. This might be confusing for users. An updated UDV tally could also be added if it's something of value.

I realise that this breaks the "official" CVSSv2 line, but we, and competitors in the majority still include Critical scoring despite the fact the CVSSv2 scores are also included per-finding. It seems to be in-demand as a client expectation (go figure!)

**Requesting the added option to have a setting to turn ON CVSSv2 support for Critical-risk scoring.  Also for the updated UDV tally in support of the request.**  

Thanks,

Sean

**Comment by BuffaloWill** [comment]
Thanks for submitting in an issue, much easier to track.

We have a code freeze starting this morning but I can get this in for the official 1.2 release Aug 1st.  I will add it to the dev build tonight after the releases are built.

**Comment by ITGSean** [comment]
Awesome - thanks :)

**Comment by BuffaloWill** [comment]
Landed, see Issue #288
