### ISSUE TITLE
Vuln ID Mapping in report generation

### ISSUE THREAD

**Issue by geckom** [SerpicoProject/Serpico#311]
## Feature Request

We need to be able to include the CVE or "Vuln ID Mapping" in the report. This is so we can add any relevant CVE numbers to our reports.

### Example Use Case

Our clients often want to know if there is a CVE related to a particular finding. While having a reference URL to a CVE is nice, we would like to include any Vuln ID mapping data in the report itself.

### Other
Obviously there is Vuln ID mapping already in Serpico, we just need to be able to display this data in the report. Vuln ID mapping doesnt show when manually adding a finding, this might influence how this is implemented.

**Comment by ITGSean** [comment]
Surely this is what the "References" field is for?

**Comment by geckom** [comment]
Was going to put it in another sections but can just use references. Closing.
