### ISSUE TITLE
Config option to turn on list item delete confirmation

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#312]
## Feature Request

Add a configuration switch to globally turn on item deletion confirmation in list views(reports/findings/users)

### Example Use Case
As more and more users are actively using Serpico, the odds of someone accidentally deleting something like a report or finding become higher.  To try to prevent this from happening, I suggest that a config option be added to enable deletion confirmation alerts when clicking a delete button in any of the list views.

**Comment by BuffaloWill** [comment]
Landed.  There is no configuration option however. It is required for all installs.
