### ISSUE TITLE
Limit user's ability to delete findings.

### ISSUE THREAD

**Issue by roobixx** [SerpicoProject/Serpico#317]
## Feature Request

Once again, love the work. This is a feature request!

I would love to be able to limit a user to only be able to add findings a report but not be able to remove them. 

Example: Two authors are working on populating a report with findings, one is the owner that has full control of the report, but the other and only add to it, not take away findings. The goal is being able to preserve the data integrity of each report when working as a team on it.

This may be a little too use-case specific for you to consider but I thought it would be worth mentioning.

**Comment by BuffaloWill** [comment]
@roobixx - Thanks for the support!  You may already know this, but generated documents and previewed findings are kept in the tmp directory of Serpico. The report name string is randomly generated but with some date-time checking and luck you can retrieve a previously generated report which might still have your finding in it.

**Comment by roobixx** [comment]
@BuffaloWill No problem.

Im more interested in findings that have been removed from a report prior to it being generated. In an ideal world, the report generation would only happen when the findings are all squared away and the report is ready for publishing.

**Comment by BuffaloWill** [comment]
I moved this to a plugin, which I think is the best place for it for now.

**Comment by roobixx** [comment]
Thanks!
