### ISSUE TITLE
Recycling Bin/trash can for deleted findings

### ISSUE THREAD

**Issue by roobixx** [SerpicoProject/Serpico#318]
## Feature Request

Looking for away to bringing back a finding into a report that was accidentally deleted from a report. 

If deleted findings landed in some sort of recycling bin, that could be reviewed prior to fully removing them from the database.

Example: Intern deletes a significant finding from the report just before publishing, you could go an restore that finding to the report with no harm. Currently, this is not possible as one the finding is delete it must be re-entered into the database.

**Comment by BuffaloWill** [comment]
Moved to a plugin issue. This is not too difficult to implement as a plugin.

**Comment by roobixx** [comment]
Love it. Thanks so much for the amazing work! Anyway to make a donation to the cause??
