### ISSUE TITLE
Include user actions in the logs

### ISSUE THREAD

**Issue by roobixx** [SerpicoProject/Serpico#319]
## Feature Request

Have an event history of when findings are added or removed from a report as well as by whom.

Example: John and Tom are co-authoring a report but one finding is missing because it was deleted. Who is the guilty party??? No, one knows...lol

**Comment by BuffaloWill** [comment]
This should be added into the logs; updated the issue title. 

Actions to add into the logs with a format of "action,time,by_whom, uri"):
- Finding is added/deleted 
- Report is generated/deleted
- User is created/deleted

**Comment by roobixx** [comment]
Dude, awesome!!!

**Comment by BuffaloWill** [comment]
Landed =)

**Comment by roobixx** [comment]
Man, you are awesome. Thanks for the work you put into such a wonderful and essential tool.
