### ISSUE TITLE
Trying to quit for each loop if result exists

### ISSUE THREAD

**Issue by rohitkapur** [SerpicoProject/Serpico#322]
## Feature Request

I'm not sure if this is already exists or not, but I couldn't figure it out.

I'm trying to quit out of a for loop if after its first run if both of the below conditions are true. In other words, I don't want to print 'Sample Text' more than one time.

### My Code

```
¬report/findings_list/findings¬
† translate(type,$up,$low)=translate('Web Application Pentest',$up,$low) †
† translate(title,$up,$low)!=translate('',$up,$low) †
        Sample Text
¥
¥
```

**Comment by BuffaloWill** [comment]
Hi @rohitkapur. This is not a feature request. Please resubmit as a feature that is missing from or as a bug in the tool.
