### ISSUE TITLE
Select Specific Paragraph in Markup

### ISSUE THREAD

**Issue by r3b00t5** [SerpicoProject/Serpico#324]
## Feature Request

If it doesn't already exist, I'd like the ability to get the contents of a specific paragraph.

### Example Use Case

Within the Serpico Web App
Affected Systems
```
California
192.168.0.1, 192.168.0.2
New York
10.0.0.1, 10.0.0.2
```

Within the Report Template
...
Below is the list of affected hosts by region:

| ¬affected_hosts/paragraph/1¬ µzzzzµ π.π ÷ π.π ≠ | ¬affected_hosts/paragraph/3¬ µzzzzµ π.π ÷ π.π ≠ |
| --- | --- |
| ¬affected_hosts/paragraph/2¬ µzzzzµ π.π ÷ π.π ≠ | ¬affected_hosts/paragraph/4¬ µzzzzµ π.π ÷ π.π ≠ |

Within the Generated Report
...
Below is a list of affected hosts by region:

| California | New York |
| --- | ---|
| 192.168.0.1, 192.168.0.2 | 10.0.0.1, 10.0.0.2 |

**Comment by frisch-raphael** [comment]
Did you try 

affected_hosts/paragraph[1]

 inside the ¬ metacharacters ?

**Comment by BuffaloWill** [comment]
hi @r3b00t5, any updates on this?

**Comment by r3b00t5** [comment]
This works in a table

|¬affected_hosts/paragraph[1]¬ µzzzzµ π.π ÷ π.π ≠|
|-|
|¬affected_hosts/paragraph[2]¬ µzzzzµ π.π ÷ π.π ≠|

|California|
|-|
|10.0.0.1|

**Comment by BuffaloWill** [comment]
Good to know. Thanks!

**Comment by r3b00t5** [comment]
One thing to note.
After some experimentation, it seems if you supply a paragraph number higher than the amount you have, Word will throw an error. It doesn't seem to affect the document contents, but it does cause you to have to go through the document recovery.

Serpico Affected Hosts Field
```
California
10.0.0.1
```
Report Template

|¬affected_hosts/paragraph[1]¬ µzzzzµ π.π ÷ π.π ≠|¬affected_hosts/paragraph[3]¬ µzzzzµ π.π ÷ π.π ≠|
|-|-|
|¬affected_hosts/paragraph[2]¬ µzzzzµ π.π ÷ π.π ≠|¬affected_hosts/paragraph[4]¬ µzzzzµ π.π ÷ π.π ≠|

`We're sorry. We can't open <Document Name> because we have found a problem with its contents.`

```
Ambiguous cell mapping encountered. Possible missing paragraph element. <p> elements are required before every </tc>.

Location: Part: /word/document.xml, Line:0, Column:0
```
Results

|California|
|-|
|10.0.0.1|
