### ISSUE TITLE
company_address and company_city missing

### ISSUE THREAD

**Issue by theguly** [SerpicoProject/Serpico#327]
creating a docx template with:
![image](https://user-images.githubusercontent.com/1745802/29421797-71e1dac6-8376-11e7-8135-f4ceb4581317.png)
and configuring report information on serpico web interface like this:
Company Address: sinatra way
Company City: mycity

generated report shows 2 blank likes where it should show sinatra way and mycity.

if i use CONTACT_ADDRESS and CONTACT_CITY it works, but i think it's not the intended use.

i had this behaviour in 1.1.0 and now in 1.2.0

**Comment by Petessss** [comment]
I'm not sure what you mean. Are you trying to print out your info the the customers?

**Comment by Petessss** [comment]
Did you update your info under the consultants information tab?

**Comment by Petessss** [comment]
there is no variable for COMPANY_ADDRESS. Only CONTACT_ADDRESS.  As the contact may be located at a different location the main company office.
