### ISSUE TITLE
Paragraph Selection throws Word Error

### ISSUE THREAD

**Issue by r3b00t5** [SerpicoProject/Serpico#329]
After some experimentation, it seems if you supply a paragraph number higher than the amount written, Word will throw an error. It doesn't seem to affect the document contents, but it does cause you to have to go through the document recovery.

#### 1. Serpico Affected Hosts Field
```
California
10.0.0.1
```
#### 2. Report Template

|¬affected_hosts/paragraph[1]¬ µzzzzµ π.π ÷ π.π ≠|¬affected_hosts/paragraph[3]¬ µzzzzµ π.π ÷ π.π ≠|
|-|-|
|¬affected_hosts/paragraph[2]¬ µzzzzµ π.π ÷ π.π ≠|¬affected_hosts/paragraph[4]¬ µzzzzµ π.π ÷ π.π ≠|

#### 3. Word Error
`We're sorry. We can't open <Document Name> because we have found a problem with its contents.`

```
Ambiguous cell mapping encountered. Possible missing paragraph element. <p> elements are required before every </tc>.

Location: Part: /word/document.xml, Line:0, Column:0
```
#### 4. Results

|California|
|-|
|10.0.0.1|

**Comment by BuffaloWill** [comment]
Hey @r3b00t5, this is an XSLT issue and beyond Serpico's scope. Serpico will add the XSLT you give it even if that breaks the XML parsed by Word.

**Comment by r3b00t5** [comment]
I figured as much. Do you know of any workarounds?

**Comment by r3b00t5** [comment]
I'll give it a shot in the next few days, thanks
