### ISSUE TITLE
Feature request: Import OpenVAS9 XML

### ISSUE THREAD

**Issue by DamienDaco** [SerpicoProject/Serpico#332]
## Feature Request

Hi, first of all, many thanks for this great tool.

I would like to import my OpenVAS-9 reports in Serpico.
I'm using the latest OpenVAS-9 packages from the Kali repo. (Latest Kali 2017.1 image)
I tried importing my reports in MSF but I wasn't very successful. (Is OpenVAS9 using a different XML format than expected?)

Here's a sample OpenVAS9 XML report I made: https://pastebin.com/0xmLQtHW

Regards,

Damien

**Comment by BuffaloWill** [comment]
Hi @DamienDaco. Data imports are a feature request for the plug-ins project (https://github.com/SerpicoProject/SerpicoPlugins) if you would it there please. We are moving away from adding tool data import to the master Serpico project.

Also, if you have a script that parses OpennVAS-9 data in ruby you can easily use Serpico scripting (https://github.com/SerpicoProject/Serpico/wiki/Automating-Serpico) to add your findings into your report.
