### ISSUE TITLE
convert effort to config variable

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#333]
Currently effort is set as a fixed list  : ["Quick","Planned","Involved"]
https://github.com/SerpicoProject/Serpico/blob/def8ffc5b9e93dabf1ff9fe39c28f32657712947/server.rb#L16

It would be good if this can also become a variable maintained via config file. 

people might want to change those to say HIGH / MEDIUM / LOW or SMALL / MEDIUM / LARGE or <1 Day, 1-5 day, > 5 day etc so better to give it as a customization option.

**Comment by BuffaloWill** [comment]
Thanks for the submission. This is landed. It will be the default for future installations of Serpico. However, to incorporate the change to an existing installation,  you will need to add the effort array to your config file. An example is shown on

https://github.com/SerpicoProject/Serpico/blob/master/config.json.defaults#L35

**Comment by anantshri** [comment]
Awesome thanks for the quick work on this one.
