### ISSUE TITLE
Options to customize TLS Setup

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#334]
There is no way to play with the TLS Settings.
1. Enable disable TLS versions
2. Enable / disable various cipher suites

I am going to make an assumption that the general idea is to run this behind a nginx kind of reverse proxy however if we are giving the option to enable SSL on it it would be ideal to enable these options also.

**Comment by BuffaloWill** [comment]
I think this will have to wait on an upgrade to a newer version of Ruby. In my testing, 2.1.5 failed to respect the disabled_cipher options introduced to webrick.

**Comment by BuffaloWill** [comment]
From the IRC discussion (thanks to @anantshri), the spec for setting ciphers:
https://github.com/theforeman/smart-proxy/pull/380/files

**Comment by BuffaloWill** [comment]
This is partially landed. We can be more granular about SSL ciphers now. To complete the feature, this should be adjustable in config.json

**Comment by BuffaloWill** [comment]
Landed. 

You can set which ciphers are enabled and disabled using the new array in the configuration file. There is an example in config.json.defaults. According to https://gist.github.com/tam7t/86eb4793e8ecf3f55037#explanation, I think should also allow disabling via ! flag.
