### ISSUE TITLE
Add Client Name to List Reports view

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#336]
## Feature Request

With a lot of reports in the "List Reports" view, can get difficult to differentiate between reports just from looking at the title.  I propose that the client name be added as a displayed column, so you see 

"Report Name      Client Name      Owner      Actions". 

Thanks

Sean

**Comment by BuffaloWill** [comment]
Good idea. This should be an easy add.

**Comment by ITGSean** [comment]
sftp://root@serpico/opt/serpico-04-09/views/reports_list.haml

Here's my edit.  Seems to work ok.

**Comment by BuffaloWill** [comment]
Thanks. Just landed this.
