### ISSUE TITLE
"File too large. 1MB limit" error on report import

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#338]
Hi

Again, not sure if this is a bug or not.

I'm individually exporting reports from our "live" serpico server which has been giving us errors when adding a new finding into a report (ie. not from findings db).  I suspect some kind of db corruption in one of the older reports which was created in an older version of serpico. So, I've spun up the latest version locally on my Kali laptop and have been importing the reports and testing for errors in each one.

I get to export/import iteration  number 4 and get this error on import:

![image](https://user-images.githubusercontent.com/25362513/30020678-98a376f8-915c-11e7-9309-85405b7aeea0.png)

Is this expected behaviour of Serpico?  One MB seems a tad small as a limit for importing a report to me.

Cheers,

Sean

**Comment by BuffaloWill** [comment]
@ITGSean that is expected behavior. I agree though, we should increase that. It's an easy enough fix.

**Comment by BuffaloWill** [comment]
Landed. Increased the import limits for findings databases and reports to 100MB.
