### ISSUE TITLE
FR: Finding author username included in findings DB view

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#343]
## Feature Request

When a non-admin user creates a report finding and then uploads to the findings DB, Serpico currently just adds the finding to the DB as not approved and that's it.  There is no way in the findings DB view to know which user uploaded the finding. In a multi-user environment it can become difficult to track down who added it. For example a Serpico admin may need to speak to the user who uploaded the finding to clarify a point before approving it.

**Comment by BuffaloWill** [comment]
Thanks for the submission. Just landed this feature.
