### ISSUE TITLE
Any recommendations to increase the speed of the application 

### ISSUE THREAD

**Issue by sandeepl337** [SerpicoProject/Serpico#349]
Hi, 

I've installed Sepico on the 16GB/500 GB HDD and I found that the application running really slow on the local network/external network. 

Do you have any recommendations to speedup the application.

**Comment by Petessss** [comment]
Can you please provide more information? What OS are you using, how much memory, how fast are the CPUs, how many users, what version of Serpico are you using (dev or installer)?

**Comment by BuffaloWill** [comment]
@sandeepl337. This sounds like a networking issue.

Serpico app itself has a small memory footprint. One exception is when generating a very large report, however this should not cause continued sluggishness.
