### ISSUE TITLE
Hyperlink in Word Template

### ISSUE THREAD

**Issue by giper45** [SerpicoProject/Serpico#350]
## Feature Request

Is there a way to insert automatic hyperlinks in Word documents that Serpico generate?

### Example Use Case
When the user insert a website (http://www.example.com) into word with Serpico Meta Language it would be useful that this link becomes an hyperlink.

**Comment by ITGSean** [comment]
+1 to that!  It's a royal pain to have to go through a report making the references hyperlinks!

**Comment by BuffaloWill** [comment]
There is not a way to do this right now that I know of. We need to look into the WordML for a hyperlink and then we can add this into Serpico.

Thanks!

**Comment by giper45** [comment]
Yeah it's right, I M trying to work at this feature and I'm going to insert
an option in config file to enable or not the hyperlink convertion... Do
you think that it s a good position set an option true or false  in
config.json file (static selection)  or it would be better a checkbox in
the report configuration view (gui selection)  to enable the hyperlink
feature?

Il 14 ott 2017 11:22 AM, "Anant Shrivastava" <notifications@github.com> ha
scritto:

**Comment by giper45** [comment]
Mmh... maybe your solution it's more simple and useful, I M going to work at it in this way because it s better I think!

**Comment by BuffaloWill** [comment]
Landed! Thanks.
