### ISSUE TITLE
Bug Report with Single and Double quotes

### ISSUE THREAD

**Issue by giper45** [SerpicoProject/Serpico#359]
## Bug 
Good morning, when  a report template which contains Word single and double quotes is loaded in Serpico, some words are cut from the process of the report generation:
 
 ### Steps to reproduce
 
 1. Insert a template report with simple and double quotes: 
<img width="760" alt="wrong_template" src="https://user-images.githubusercontent.com/18548727/31316066-ad3e7110-ac25-11e7-8102-aec1d9bc7980.png">

 2. Generates a report, and look that the report is missing words between quotes:
<img width="667" alt="cutted_terms" src="https://user-images.githubusercontent.com/18548727/31316079-ed0f5598-ac25-11e7-9979-88597b2ed6db.png">

 
 
 
The issue is serious enough for italian users, because a lot of words are with single quotes ( maybe it's because I'm italian that I've found this :) ! ) 

## Feature Request
By adding the following lines :

<img width="698" alt="request" src="https://user-images.githubusercontent.com/18548727/31316099-8fcd1da6-ac26-11e7-95cb-0e8a72e3c4c3.png">
to /Serpico/helpers/xslt_generation.rb file, in generate_xslt function the problem seems to be solved: a convertion in simple quotes is done when the user add / edit a new word template.

if you could insert this in next Serpico release, me and my team would be very grateful (I could send a pull request if I have to do).
Thanks in advance.

"

**Comment by BuffaloWill** [comment]
@giper45 Thank you for the detailed bug report and patch!! It is merged into master now.

**Comment by giper45** [comment]
Hi @BuffaloWill, another "stripping character seems to be the "–" (different from -), try to submit the following string in a template:
```
ICT Risk Management – Code Review Analysis Light  – BLABLABLABLABLA

```
(no - but – ) , 
it returns: 
```
ICT RiskReview Analysis  
```
If you can try to solve this issue with the same find and replace method... 

Thanks in advance!
