### ISSUE TITLE
Multiple Consultants Meta Language

### ISSUE THREAD

**Issue by morganh83** [SerpicoProject/Serpico#361]
## Feature Request

Would like to have meta language for adding multiple consultants to a report.

**Comment by frisch-raphael** [comment]
Hi morganh83,

I don't know if Serpico has any project to support multi consultants reports, but for now you can always create UDOs (https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Objects) as an alternative

**Comment by morganh83** [comment]
I will give that a go. Thanks.
