### ISSUE TITLE
[question] Deploy Serpico on a server

### ISSUE THREAD

**Issue by TKSS3** [SerpicoProject/Serpico#362]
Hi,

I have the developer version of Serpico and want to deploy my version on a server. 
What is the best way to do this? I coudn't find an export script or something for the whole project.

**Comment by Petessss** [comment]
With the exception of having to reinstall the gems (bundle install should fix that), you should be able to copy the serpico folder over to the new system/server.

**Comment by Petessss** [comment]
You can copy the serpico folder over to the new system and run bundle install to install all the gems. Also make sure you have all the dependencies listed in https://github.com/SerpicoProject/Serpico/wiki/Developer-Build

**Comment by TKSS3** [comment]
Okay, thank you. So no need to run first time script or something?
