### ISSUE TITLE
Fix Indentation Issues

### ISSUE THREAD

**Issue by BuffaloWill** [SerpicoProject/Serpico#364]
## Feature Request

As pointed out by @frisch-raphael in IRC, the serpico code indentation is inconsistent to put it politely. It could use cleaning up and the ruby style guide (https://github.com/bbatsov/ruby-style-guide) good practices was suggested. 

TLDR Result from this issue should be consistent application of indentation following https://github.com/bbatsov/ruby-style-guide

**Comment by 42flyingfish** [comment]
May I take a shot at this?

**Comment by frisch-raphael** [comment]
I have already used rubocop (https://github.com/bbatsov/rubocop) on my whole project, I can do a pull request if you want

**Comment by BuffaloWill** [comment]
So.. in talking to Bokojan I realized I made a mistake in applying the help wanted label. I will self assign this issue. It will be faster for me to do it then read through every single line of a PR.

Thank you to @42flyingfish for the offer and @frisch-raphael for being awesome on the submission.

**Comment by BuffaloWill** [comment]
Also @42flyingfish if you are looking to contribute, PR's related to https://github.com/SerpicoProject/Serpico/issues/346 are not too hard. We can incrementally solve this issue if people start to submit PR's for it.
