### ISSUE TITLE
Image Captions and tag headers

### ISSUE THREAD

**Issue by giper45** [SerpicoProject/Serpico#367]
## Feature Request
Hi, just two simple questions; 
1. When I insert an image in upload attachments:
<img width="306" alt="example_serpico" src="https://user-images.githubusercontent.com/18548727/31672659-755fc39a-b35d-11e7-8382-f753293659de.png">

There is a "caption" parameter; anyway, when the image is rendered on the word document, the image has not a caption text of the image. Is this parameter designed to appear on the word document as caption?

2. What about choose the "horizontal alignment" of the image during the loading? When they are drawed I always have to move them on center (because I prefer that they are on the center); could be a useful feature? 

3.  ƒh4ƒ is called by inserting [== Heading text goes here ==] right? There is no way to insert multiple levels of header? (For example fh4f  could be called with [==== Heading text goes here ====] , while fh3f could be called with [=== Heading text goes here ===], and in the template different format could be used with these different headers (a larger header for fh3f, while a smaller with fh2f) 

Thanks in advance!

**Comment by frisch-raphael** [comment]
I'm interested in 2. I briefly tried to do it a while ago and stopped when I figured it wasn't as easy as I thought it would (I think you have to center the paragraph tag that the image is added into, and not the image tag itself).
If you want to implement 2, and if you do have to modify the parent paragraph tag, I would suggest using nokogiri (http://www.nokogiri.org/tutorials/searching_a_xml_html_document.html) to find and modify it. I've found out while developing a new feature that this is much easier than regexing your way through the wordml

**Comment by BuffaloWill** [comment]
@gipher45, thank you for submitting. Please create separate issues for each bug or feature. Questions should be addressed in IRC or via the slack channel. 

on 3.; this is an interesting feature request. Ideally we'd like to get a full markdown editor into the finding and I think this would fit into the spec for it. There have been suggestions of third party markdown editors to incorporate but no progress has been made on incorporating them. 

Cheers!
