### ISSUE TITLE
Adding Netbios and OS from Nessus into Reports

### ISSUE THREAD

**Issue by markajbell** [SerpicoProject/Serpico#368]
## Feature Request

Is there a way to get the Netbios data into the report from Nessus?
I currently have a report setup in word that lists the Vulnerability by Severity and then by IP, Netbios and OS. Can i replicated this within Serpico??

**Comment by ITGSean** [comment]
Doubtful - there's no support for even port scans :(

**Comment by Petessss** [comment]
This would be a great candidate for a plugin. Check out https://github.com/SerpicoProject/SerpicoPlugins/tree/master/BurpAppendix for an example.
