### ISSUE TITLE
Image Caption explanation

### ISSUE THREAD

**Issue by giper45** [SerpicoProject/Serpico#369]
## Feature Request
Hello, when I insert an image in upload attachments:
<img width="306" alt="example_serpico" src="https://user-images.githubusercontent.com/18548727/31672659-755fc39a-b35d-11e7-8382-f753293659de.png">

There is a "caption" parameter; anyway, when the image is rendered on the word document, the image has not a caption text of the image. Is this parameter designed to appear on the word document as caption?

Thanks in advance!

**Comment by BuffaloWill** [comment]
Hey @giper45, the caption is stored in the DB with the image but this is no implemented yet in the markup. I removed this field from master for now, until we get the caption working with the documents.
