### ISSUE TITLE
Multiple header syntax

### ISSUE THREAD

**Issue by giper45** [SerpicoProject/Serpico#371]
## Feature Request
Hello.
ƒh4ƒ is called by inserting [== Heading text goes here ==] right? There is no way to insert multiple levels of header? (For example fh4f  could be called with [==== Heading text goes here ====] , while fh3f could be called with [=== Heading text goes here ===], and in the template different formats could be used with these different headers (a larger header for fh3f, while a smaller with fh2f).
Thanks in advance

**Comment by BuffaloWill** [comment]
You are correct, this is not implemented. 

Overall we need to empower the user more with the markup components. I think implementing a markdown editor into the findings is the best path but we are not there yet. Closing this issue and referencing https://github.com/SerpicoProject/Serpico/issues/243
