### ISSUE TITLE
Ruby Version on kali 64-Bit 2017.2

### ISSUE THREAD

**Issue by jauharvp** [SerpicoProject/Serpico#378]
# Please fill out the Bug Form or Feature Request Below
root@kali:/opt/Serpico/Serpico# ruby serpico.rb 
Your Ruby version is 2.3.3, but your Gemfile specified 2.1.5
-------------------
## Bug
Describe the issue and steps to reproduce

1. ...
2. ...

## Feature Request

Describe the feature and give an example use case

### Example Use Case

"As a user ..."

**Comment by Petessss** [comment]
You can use RVM (https://github.com/SerpicoProject/Serpico/wiki/Developer-Build) or a release version https://github.com/SerpicoProject/Serpico/releases/tag/1.2.1.
