### ISSUE TITLE
Feature request: Integrate Nmap result for the report as like Nessus & Burp

### ISSUE THREAD

**Issue by jauharvp** [SerpicoProject/Serpico#379]
## Feature Request

The integrating of Nmap result using xml file would me much help full to create report for Infrastructure

### Example Use Case

The Nmap results integration to show vuln list and the pie chart based  on the Nmap result as like Nessus and Burp. @BuffaloWill

**Comment by Petessss** [comment]
The would make a great plugin. See https://github.com/SerpicoProject/SerpicoPlugins for examples.
