### ISSUE TITLE
Duplicate listing of vulnerability - Nessus Import

### ISSUE THREAD

**Issue by jauharvp** [SerpicoProject/Serpico#380]
#Bug Duplicate listing of vulnerability in serpico

-------------------
## Bug
Describe the issue and steps to reproduce

1. Scan targets in Nessus in Advanced Scan and in Basic Network
2. Upload both results to the Serpico
@BuffaloWill

**Comment by BuffaloWill** [comment]
@jauharvp thanks for the issue and sorry for the slow response; vuln import issues have a backlog right now.

**Comment by jauharvp** [comment]
Much appreciated and love to use serpico

**Comment by BuffaloWill** [comment]
This is a duplicate of https://github.com/SerpicoProject/Serpico/issues/330; closing.
