### ISSUE TITLE
Bug insertion of image

### ISSUE THREAD

**Issue by giper45** [SerpicoProject/Serpico#381]
## Bug
I think that commit "628c666c8f7beb800787261a4299326694d38964" that removed caption until implementations have created an issue to upload images:

### Steps to reproduce 
1. Upload an image in upload attachments

2. The exception appears:
<img width="652" alt="2017-11-12 16_27_13-nomethoderror at _report_20_upload_attachments" src="https://user-images.githubusercontent.com/18548727/32700822-cd000bba-c7ca-11e7-8248-20756d808d6f.png">

This is related to following problem:
in helper.rb, line 208:
```ruby
   hash.each do |k,v|
                v = CGI::escapeHTML(v)

    if v
                        # convert bullets
                        v = v.gsub("*-","<bullet>")
                        v = v.gsub("-*","</bullet>")

....

```
CGI:escapeHTML is called without checking if v exists; now the code reads the k key ("caption", that is not implemented for the moment), but doesn't find v; 
the solution could be moving CGI:escapeHTML in the if loop:

```ruby
   hash.each do |k,v|

    if v
                        v = CGI::escapeHTML(v)
                        # convert bullets
                        v = v.gsub("*-","<bullet>")
                        v = v.gsub("-*","</bullet>")

....

```

**Comment by BuffaloWill** [comment]
Confirmed. Thanks @giper45 for the detailed issue. I just pushed a fix.
