### ISSUE TITLE
How to count findings by category?

### ISSUE THREAD

**Issue by TKSS3** [SerpicoProject/Serpico#382]
Hi,

Is there a way to count each finding by it's category? So you can say in the report: During the assessment, one high, two medium and three low risk issues were identified.

I've found this issue: https://github.com/SerpicoProject/Serpico/issues/245, but that doesn't seem to work.

**Comment by BuffaloWill** [comment]
Hi @TKSS3, yes. The finding tally [reserved UDV's](https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Variables#reserved-udvs) are what you are looking for.

**Comment by TKSS3** [comment]
Thank you :)

**Comment by TKSS3** [comment]
It isn't working as i expected.

I've got this table:

§critical_tally§ | critical
§high_tally§ | high
§moderate_tally§ | medium
§low_tally§ | low
§informational_tally§ | informational

Only this is what i get with one medium (score = 4.3) finding using CVSSv3.
1 | critical
0 | high
0 | medium
0 | low
0 | informational

This also happens with 5 low findings with a CVSSv3 score of 0.0
4 | critical
1 | high
0 | medium
0 | low
0 | informational


I'm not sure if I'm doing something wrong, or if this is a bug.

**Comment by BuffaloWill** [comment]
That sounds like a bug. I am surprised though because the feature is simple.

Here is the [code that does the work](https://github.com/SerpicoProject/Serpico/blob/8c7d566da08198f9ba6760f7320dbc29c567cc08/helpers/helper.rb#L168). It just adds up the tally based on cvss score. 

Can you take screenshots of the findings list and from the report?

**Comment by BuffaloWill** [comment]
What is you configuration option set to for scoring?

**Comment by TKSS3** [comment]
> What is you configuration option set to for scoring?
> 
> Might be a bug, if the user's configuration option for scoring is different from the report's scoring.

The Risk Scoring Algorithm at "Configuration Options (Must Restart After Changes)" is set to default. My report scoring is set to CVSSv3.

Once I've changed it from default to CVSSv3 it works, as expected. But there is one thing I do not agree on. On this page: https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Variables#reserved-udvs it says "0 - 3.9 : low", but I think it would be better if "0.1 -3.9 : low" and "0 : informational".

Just like this is "none": https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:P/AC:H/PR:H/UI:R/S:C/C:N/I:N/A:N

And this one is "low":
https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:P/AC:H/PR:H/UI:R/S:C/C:L/I:N/A:N

**Comment by BuffaloWill** [comment]
Thanks @TKSS3. I will update the tally to reflect informational and fix the bug with config_option.

**Comment by BuffaloWill** [comment]
@TKSS3, informational tally count should be fixed now. I'll create a config_option issue to track.

**Comment by TKSS3** [comment]
No problem, thank you for helping me!
