### ISSUE TITLE
&-sign gets removed

### ISSUE THREAD

**Issue by TKSS3** [SerpicoProject/Serpico#386]
## Question / Bug
&-symbol gets removed from generated template.
For example:
ben&jerry -> benjerry
ben & jerry -> ben  jerry

The only weird thing is, it doesn't happen to the &-symbol that already is in "Default CVSSv3 Template" (maybe other templates), but if i add my own (for example ben&jerry), it gets removed

#### Template:
![proof1](https://user-images.githubusercontent.com/14976727/32938781-9d3ea204-cb7d-11e7-9327-be934501fb48.PNG)

#### After generated:
![proof2](https://user-images.githubusercontent.com/14976727/32938784-9f35bcb4-cb7d-11e7-87cd-3430f97edadf.PNG)

As you can see the &-symbol got removed at ben&jerry, but not at C&C.

#### How to reproduce:
1. add ben&jerry and ben & jerry to your template
2. upload template
3. select template
3. generate report with template

Am I doing something wrong or is this a bug?

EDIT:
I've found this issue: https://github.com/SerpicoProject/Serpico/issues/236, but it's closed and do not see a solution yet.

**Comment by BuffaloWill** [comment]
@TKSS3, thanks for the detailed issue. I need to look into this more. I thought we had fixed this, but it doesn't look like it. What version of Word are you using?

On the "C&C", I believe that is an image so the parser is going to ignore that on import.

**Comment by TKSS3** [comment]
@BuffaloWill, glad I can help. I'm using Word 2013. 

And you are right with the "C&C". If I add ben&jerry and ben & jerry to the "super fancy flow chart", they both keep there ampersand.

### Template:
![proof3](https://user-images.githubusercontent.com/14976727/33007442-148c2d74-cdcf-11e7-89a6-1ebb99fe2c1d.PNG)

### After generated:
![proof4](https://user-images.githubusercontent.com/14976727/33007443-14bf6dc4-cdcf-11e7-88d8-07854e83c994.PNG)

**Comment by BuffaloWill** [comment]
I /think/ https://github.com/SerpicoProject/Serpico/pull/482 should fix this, closing as it is tracked in https://github.com/SerpicoProject/Serpico/issues/398
