### ISSUE TITLE
Counter for loops

### ISSUE THREAD

**Issue by atta1993** [SerpicoProject/Serpico#390]
## Feature Request

A counting variable to use inside loops.

### Example Use Case

It would be handy to enumerate findings, so one could have numbered subsections for findings. Or refer to findings by number, especially in a findings table.

**Comment by balmohan** [comment]
Yes its must be there I am trying to do it but no luck.

**Comment by BuffaloWill** [comment]
Thanks for the submission @atta1993. I will look at this. Have you tried using a numbered list with your for loop? Word may automatically number it for you; I haven't tested this.

**Comment by BuffaloWill** [comment]
Closing until updated.
