### ISSUE TITLE
Search Option in Report List

### ISSUE THREAD

**Issue by sho-luv** [SerpicoProject/Serpico#391]
## Feature Request

A search option on the https://<ip>:<port>/reports/list

page that allows you to search for reports by username and or name of the report. Currently I use the browsers search page features. However if I could search and get a list of only the items that fit the search showed up that would be useful. Also a select all option would be useful.  

### Example Use Case

As a user I search for reports that were created by the user sho_luv. Then I could select all of them and delete them.

I have a lot and I have to search them with the browser currently and then delete them one by one.

**Comment by BuffaloWill** [comment]
Thanks @sho-luv. The current version has the ability to search for report names and a select all feature. We do not have the ability to search by author though. 

Developer notes: 
- Need to figure out searching on multiple fields or create multiple search boxes

**Comment by BuffaloWill** [comment]
Closing this unless other people ask for it. Searching on multiple fields is not in the pipeline right now.
