### ISSUE TITLE
I can't be able to install On window 10

### ISSUE THREAD

**Issue by Marlene-Lwin** [SerpicoProject/Serpico#396]
# Please fill out the Bug Form or Feature Request Below

I would like to let you know that Serpico is not being installed on window
when I am trying to install serpico on My window. output is shown like below
**An error occurred while installing json (1.8.6), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.6'` succeeds before bundling.

In Gemfile:
  data_mapper was resolved to 1.2.0, which depends on
    dm-serializer was resolved to 1.2.2, which depends on
      json**

-------------------
## Bug
Describe the issue and steps to reproduce

1. ...
2. ...

## Feature Request

Describe the feature and give an example use case

### Example Use Case

"As a user ..."

**Comment by Petessss** [comment]
How are you installing Serpico? Are you using the installer? If so, what version.

**Comment by Petessss** [comment]
Using a clean Windows 10 Pro N install with Serpico 1.2.2 windows installer; I'm unable to reproduce this issue.

**Comment by Marlene-Lwin** [comment]
I would like to know that where can i download window Installer.
curently I download git clone folder and ruby 2.2. and 2.3.3 verions.

**Comment by Petessss** [comment]
You can download the windows installer from https://github.com/SerpicoProject/Serpico/releases/tag/1.2.2.1

**Comment by sharmaaddy** [comment]
What is the user id and password for windows installation? I did not see it any where?
