### ISSUE TITLE
Unable to bind to anything but 127.0.0.1 on 1.2.2

### ISSUE THREAD

**Issue by bandrel** [SerpicoProject/Serpico#397]
Using the new version 1.2.2 I am unable to bind to 0.0.0.0.  No matter what is included in the conf it always uses 127.0.0.1 for the binding. 

I was able to get it working by adding changing the server_options section of serpico.rb from

`server_options = {
  :Port => port,
  :BindAddress => bind_address,
}
`
to 
` 
server_options = {
  :Port => port,
  :BindAddress => bind_address,
  :Host => bind_address,
}
`
but I'm not a ruby programmer so I don't know if this was correct to do or not so I didnt want to submit a PR.

**Comment by Petessss** [comment]
@bandrel what os are you running 1.2.2 on?

**Comment by bandrel** [comment]
14.04 Ubuntu

**Comment by bandrel** [comment]
Also it happens with both the deb and the development build. I think it is related to an updated version of the webrick piece.

**Comment by Petessss** [comment]
Thank you, we'll take a look.

**Comment by BuffaloWill** [comment]
Thanks @bandrel! I just pushed a fix, let me know if it fixes for you.

**Comment by BuffaloWill** [comment]
New build is out in releases. Thanks to @Petessss for the quick build.
