### ISSUE TITLE
Dashboard chart interprets "informational" findings as "low"

### ISSUE THREAD

**Issue by prngleo** [SerpicoProject/Serpico#399]
## Bug
The dashboard findings chart adds the informational findings to low findings.

1. Add low finding.
2. Add informational finding.
3. The chart shows 2 low findings.

![s_chart](https://user-images.githubusercontent.com/6142178/34648851-0d0567b2-f3ab-11e7-837d-aa58596d8512.png)

**Comment by BuffaloWill** [comment]
Confirmed. 

IIRC the background for this issue was at one point there was a scoring algorithm which did not have an informational level. The fix isn't too difficult for default scoring, but need to do some checking for other scoring algorithms.
