### ISSUE TITLE
Findings Database Search: weird behavior with spaces

### ISSUE THREAD

**Issue by schrnz** [SerpicoProject/Serpico#402]
## Bug

The search bar in the findings database shows somewhat unexpected behavior: 
When searching for keywords that appear in findings' names, it works as expected.
However, as soon as we have a space in between 2 keywords, the search fails even though both keywords are in a finding's name (even in the very same order).

How to reproduce:
(I assume you have imported the default findings)

1. go to "Findings Database"
2. enter "Cross" into the search field. The finding "Cross Site Scripting (XSS)" is the only one left.
3. enter "Cross Site" into the search field. This time, no results are shown even though it is clearly a substring of "Cross Site Scripting (XSS)".
4. enter "Cross Site Scripting (XSS)". Also no result for a perfect match.

I do not really understand this way of searching... perfect matches do not work and keyword search only seems to work if there is no whitespace o.O

**Comment by BuffaloWill** [comment]
Thanks @schrnz. 

The search is built using CSS and javascript. The data indexing field (data-index) was indexing the title with the spaces removed.

Just pushed out a fix.
