### ISSUE TITLE
Any Nessus file will not Import

### ISSUE THREAD

**Issue by markajbell** [SerpicoProject/Serpico#404]
-------------------
## Bug
Similar issue to #401 but local nessus file.
When i upload any nessus file it uploads but then says no findings available
![image](https://user-images.githubusercontent.com/12258764/35302439-61159dd0-0086-11e8-806f-7d7cfadd0770.png)

I have downloaded the latest Windows version 1.2.2.1 and deleted and re-installed with the same effect.

**Comment by Petessss** [comment]
please provide more information. Did you follow https://github.com/SerpicoProject/Serpico/wiki/Import-Vulnerability-Scan-Data?

**Comment by markajbell** [comment]
Yes. Thanks. All works now. Nessus & Burp were enabled but not the Auto_import.

MArk
