### ISSUE TITLE
Support non-ISO date format for assessment_end_date/assessment_start_date

### ISSUE THREAD

**Issue by markajbell** [SerpicoProject/Serpico#408]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Can you change the date format to UK?
1. In the report the date is showing 2018/01/03 or 01/23/2018 instead of 03/01/2018 & 23/01/2018 . Can this be done in the template to format the either UDV or ...Ωassessment_end_dateΩ as a UK date

**Comment by BuffaloWill** [comment]
This issue starts at the browser level. Although the date selection might be regionalized, it sends it to Serpico and saves as ISO format (yyyy-mm-dd). For us to switch it would require some date conversions on the backend along with updates to the configuration to allow the user to select their date region. It's not trivial. TBH with limited resources it's going to go into backlog. If other users would like to see this added, we can always revisit it.

**Comment by markajbell** [comment]
Thanks @BuffaloWill. I have resolved with UDV instead. All works well.

 

Mark

**Comment by BuffaloWill** [comment]
Awesome @markajbell. Thank you for following up. I will close the issue.
