### ISSUE TITLE
.PNG image as attachment produce error when generating report -Windows Build

### ISSUE THREAD

**Issue by najmisyahir** [SerpicoProject/Serpico#410]
## Bug
PNG image as attachment produce an error when generating error

1. Using the latest serpico by cloning the directory
2. Running on Windows with rail installer
3. Uploaded .png image and the system produce an error when clicking generate button

Below are the error exception when clicking generate report
![ss](https://user-images.githubusercontent.com/7720161/35758061-f1feeb02-08ac-11e8-8b13-ec42c2a04bb0.PNG)

**Comment by BuffaloWill** [comment]
Hi @najmisyahir. Can you (1) verify the image is a png and (2) that it was properly uploaded (i.e. listed in uploads)?

**Comment by najmisyahir** [comment]
Hi @BuffaloWill thanks for your reply and credit for this great reporting tools, yes i've verified the image as an png format taken from this url : [https://ps.w.org/contact-form-7/assets/screenshot-1.png?rev=1176454](url). The image is uploaded onto the system without a problem, below image are the file created in the attachment folder which i can open it with paint without any issue. 
![attach_web](https://user-images.githubusercontent.com/7720161/35762187-b9c25adc-08cd-11e8-99eb-3faf7f16cd1f.png)

And the attachment are added to the report finding and it is exist when i type in the bracket for attachment insertion.
![attach_web](https://user-images.githubusercontent.com/7720161/35762203-dda817ca-08cd-11e8-95a6-6969f275d477.png)

Btw thanks again for your help @BuffaloWill

**Comment by BuffaloWill** [comment]
Thanks @najmisyahir. Could you verify that if you press generate report it still throws an error?

**Comment by najmisyahir** [comment]
I've verified it just now, testing with a new screen shot from MS paint and clicked generate report produce the same error @BuffaloWill

**Comment by frisch-raphael** [comment]
That's weird, I downloaded the png at your url ( https://ps.w.org/contact-form-7/assets/screenshot-1.png?rev=1176454), and I managed to generate a report with it.
Could you verify that when you upload your image, the path registered in the database does link to the correct png ?

For that :

cd ./db
sqlite3 master.db
select * from attachments;
select filename_location from attachments where filename = '[[your_png_filename]]'

this should give you a local path to your image

**Comment by najmisyahir** [comment]
Hi @frisch-raphael , here i include the attachment file from serpico local attachment folder
[attachments.zip](https://github.com/SerpicoProject/Serpico/files/1695359/attachments.zip)

And i checked the database that the entry for those attachment is created
![capture](https://user-images.githubusercontent.com/7720161/35808269-3914498c-0ac0-11e8-8b71-4504e3d0cd1f.PNG)

Just a question @frisch-raphael it seems that you run serpico on a ubuntu machine?

**Comment by frisch-raphael** [comment]
I'm running Serpico on Debian (well, Kali actually).
I think Serpico manages to find the image, but for some reason has problems accessing the width and height data from the png. 
Could you comment out those three lines, and try to generate the report ?

  elsif png?(img_data)
    width = IO.read(image.filename_location)[0x10..0x18].unpack('NN')[0]
    height = IO.read(image.filename_location)[0x10..0x18].unpack('NN')[1]

If what I suspect is correct, you should be able to generate the report, but the screenshots won't be resized to fit inside word

**Comment by najmisyahir** [comment]
It works! Commenting out those 3 lines solve the error
```
#elsif png?(img_data)
#width = IO.read(image.filename_location)[0x10..0x18].unpack('NN')[0]
#height = IO.read(image.filename_location)[0x10..0x18].unpack('NN')[1]
```
@frisch-raphael however it is as you said you ran it on Debian, when i setup serpico from my ubuntu vm, it ran without any problem, the png are generated with the report. Maybe there is something not worked properly on Windows build. BTW should i close this issue?

**Comment by BuffaloWill** [comment]
I think we need to test more if this is an issue with all image insertions on Windows or just this image/installation/permissions.

If it is related to Windows we could do a check if the install is Windows and disable resizing.

**Comment by ImAnEnabler** [comment]
directly related to this issue, I found the following worked on my Windows host:

```
	width = File.binread(image.filename_location, 64)[0x10..0x18].unpack('NN')[0]
	height = File.binread(image.filename_location, 64)[0x10..0x18].unpack('NN')[1]
```
