### ISSUE TITLE
Test reserved UDV (tally)

### ISSUE THREAD

**Issue by r-elliot** [SerpicoProject/Serpico#415]
Hello,
I am currently playing with Serpico to generate report and I am getting stuff done but I am stuck with an issue.
I was wondering if I could get some help here.

 I am trying to test the reserved UDV like so : 
† §critical_tally§ > 0 † 
Warning : critical(s) finding(s)
¥

But it doesn't seem to work. I searched but couldn't find a way to make this work.
 Is there a way to do what I am trying to do ? Thanks

**Comment by frisch-raphael** [comment]
Hello r-elliot,

This sould work :

† /report/udv/critical_tally > 0 †
Warning : critical(s) finding(s)
¥
