### ISSUE TITLE
Consistent release names

### ISSUE THREAD

**Issue by schrnz** [SerpicoProject/Serpico#420]
## Feature Request

I would like to suggest using a certain scheme to name release packages. In the past, releases were named along the lines of ```serpico_<version>_<platform>.<ending>```, but the naming is not perfectly [consistent](https://github.com/SerpicoProject/Serpico/releases). This triggers problems if you want to automate downloading and installation.

### Example Use Case

Right now it is hardly possible to automate the download of a certain version of Serpico (e.g., for docker) since the release packages do not strictly follow a naming scheme. Take the ```.deb``` package:  

| Version  | Released Package |
| ------------- | ------------- |
| 1.2.2.1  | serpico_1.2.2_amd64.deb  |
| 1.2.2  | serpico_1.2.2.20180102141328-1_amd64.deb  |
| 1.2.1  | serpico_1.2.1_amd64.deb  |

The name for 1.2.2 does not follow the scheme indicated by the others and the one for 1.2.2.1 is either the same as the one for 1.2.2 or there is an error in the naming. Hence, if you want to create a docker setup where you just need to configure the version number, you are lost as of now. 

### Suggestion

I would suggest to use a script or some way of automation to handle the consistent naming of releases. [This](https://developer.github.com/v3/repos/releases/#create-a-release) GitHub page describes how a user with push privileges to a repository can script the release process.

**Comment by Petessss** [comment]
Noted.

**Comment by BuffaloWill** [comment]
Updated previous releases to match naming convention. Cheers!
