### ISSUE TITLE
Unable to generate more than 10 finding in the report

### ISSUE THREAD

**Issue by exrienz** [SerpicoProject/Serpico#422]
1. Use the default Serpico - No Dread template
2. Default scoring = DREAD

As a user, i had imported the nessus file to the serpico. Once success, i removed several unnecessary findings and only left the finding as follows:

![image](https://user-images.githubusercontent.com/14239668/36156921-8a58ff14-1113-11e8-94ff-edfd9582077d.png)

However, when i tried to generate the report. Only 10 finding was able to print out to the word file. What happen?

**Comment by Petessss** [comment]
This is usually related to an issue with the markup in one of the findings. Review the markup for each finding. In some cases its the one right after the last one printed in the report.

**Comment by exrienz** [comment]
Hi Pete,

Thanks for the prompt response, you correct! Its now showing the expected result. Thanks!
