### ISSUE TITLE
Compare Nessus findings to Database (feature request)

### ISSUE THREAD

**Issue by tvvoorst** [SerpicoProject/Serpico#423]
-------------------
## Feature Request

I'm trying to have a custom Remediation automatically applied to the results of a .nessus import based on the name of the vulnerability. However the only way I'm able to do this is by editing and savings the results from Nessus to the database. After that you have to manually click all the vulnerabilities found, which is alot of work if the file is big. Is there any way to automate this?

**Comment by BuffaloWill** [comment]
@tvvoorst, have you checked out https://github.com/SerpicoProject/Serpico/wiki/Import-Vulnerability-Scan-Data? I believe auto-import is what you are looking for.

**Comment by tvvoorst** [comment]
@BuffaloWill, I did find that option and tried using it. However it does not seem to do what I want. Id like to import .nessus, add these options to findings (So far so good). Now I want these nessus findings to automatically take the information & resolution files from a matching finding in the database. Is this possible? Sorry if my explanation  is close to terrible and i appreciate the help.

**Comment by tvvoorst** [comment]
So instead of using the resolution from nessus id like to automatically add my own (different language) if the title of the finding matches.
