### ISSUE TITLE
Finding Request Max Size On Save

### ISSUE THREAD

**Issue by blawless** [SerpicoProject/Serpico#429]
## Bug
If you try to save a finding with a large amount of text in any of the input fields the page will reload to the Current Findings view but when you open the Finding you just saved, nothing has been saved.  I'm unsure on the exact size/amount of characters needed but I keep running into this lately with big findings that have a lot of text. This is in Chrome, I'm unsure if it's a POST limit, the webserver or Serpico itself.

1. Create a new report.
2. Create a new finding.
3. Enter a long string about 300-400 lines of words/content into any input box.
4. Give the Finding a title.
5. Hit save.
6. The Current Findings page loads up - open the issue you just made
7. Observe the text/words you just entered are not there... and the input box is blank.

**Comment by frisch-raphael** [comment]
One thing to note on that type of issue :

Currently, Serpico ignores datamappers' errors when it saves/edit an object. While it wouldn't fix this problem, it would be a lot less confusing for the user if an error message was returned instead of transparently pursuing. Something like this should be added everytime we save/update a datamapper object :

```
  #test for datamapper errors
  if @finding.update(data)
    # Update the finding with templated finding stuff
  else
      return "<p>The following error(s) were found while trying to update : </p>#{finding.errors.join('<br/>')}"
  end

```

**Comment by BuffaloWill** [comment]
This is a great point, I didn't realize that was happening. Let's get the error messages added.

**Comment by BuffaloWill** [comment]
I added the error response if Datamapper can't update a report or finding. Most of the columns look to have a max of 20KB, are there any that you are regularly hitting the max on? If so I can update those fields.
