### ISSUE TITLE
Msf::RPC::Exception at /report/1/services Client not authenticated

### ISSUE THREAD

**Issue by mcomtzg** [SerpicoProject/Serpico#431]
# Please fill out the Bug Form or Feature Request Below

THe integration with metasploit doesn't work fine on Kali Linu, version: Serpico-1.2.2.1

-------------------
## Bug
Describe the issue and steps to reproduce

1. Start Metasploit
2. Execute msfrpcd -U $username -P $password --ssl
3. Check on Serpico
 --> METASPLOIT DATA MANAGEMENT
 ---> Hosts

Msf::RPC::Exception at /report/1/hosts
Client not authenticated
file: client.rb location: call line: 111
![notauth](https://user-images.githubusercontent.com/36385615/37559766-1dad3b04-29f1-11e8-88de-7c1e18505e5a.png)

**Comment by mcomtzg** [comment]
![screenshot at mar 17 14-43-04](https://user-images.githubusercontent.com/36385615/37559792-97b95e14-29f1-11e8-93f6-6c19615dce3e.png)

**Comment by BuffaloWill** [comment]
Thanks @mcomtzg, should have a fix for this soon. In the meantime, Serpico 1.2.1 is working correctly with MSF. Sorry about that.

Closing, as this issue is already tracked in
https://github.com/SerpicoProject/Serpico/issues/424
