### ISSUE TITLE
OpenSSL Issues

### ISSUE THREAD

**Issue by Phr33fall1** [SerpicoProject/Serpico#432]
Hey there,

Firstly, congratulations on Serpico, I've been playing around with this to get a better understanding and I am really impressed!

Once installed and running, I conduct a local host scan and Nessus is reporting a number of OpenSSL issues. It recommends updating OpenSSL. I was wondering if updating OpenSSL will cause any problems?

Many thanks,

Phill.

**Comment by BuffaloWill** [comment]
Just pushed a fix for the SSL ciphers. Please re-scan and see if this is still an issue.
