### ISSUE TITLE
Two Factor Authentication Option

### ISSUE THREAD

**Issue by smokedawg26** [SerpicoProject/Serpico#436]
## Feature Request

Does Serpico have the option for two factor authentication?

### Example Use Case

We have a team of users that currently have to VPN into our environment in order to access our Serpico server.  If we have two factor authentication enabled, then we can publish our site to the internet so that users can access without having to VPN.

**Comment by BuffaloWill** [comment]
Hi @smokedawg26. Serpico does not and we are not planning to add it to Serpico core. This functionality could be done with a plugin. For example, integrating Duo's ruby library into the login via plugin. Duo (and others) also offer SSH 2FA; you could keep Serpico as a local service and then have users SSH proxy to it, imo more maintainable than VPN.
