### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by bahs123** [SerpicoProject/Serpico#437]
## Feature Request

Hi,

when we navigate to the current findings and in each listed vulnerabilities I need to add two extra text  fields called **defect id** for tracking the defects and **business priority** from compliance team for my project.
can you suggest any solutions/code/plugins towards the same cause?

Much appreciated..thanks! ~S

**Comment by BuffaloWill** [comment]
Hi @bahs123. This can be done with UDOs:

https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Objects
