### ISSUE TITLE
Haml::TempleEngine: Option :encode_html is invalid

### ISSUE THREAD

**Issue by sharathunni** [SerpicoProject/Serpico#441]

**Comment by sharmaaddy** [comment]
Did you get a resolution for this? I have a similar error and my reports are generated empty.

**Comment by BuffaloWill** [comment]
We should get this fixed, re-opening this issue to track it. AFAIK it does not impact usage, but is annoying to see in output.

**Comment by Storm75** [comment]
Just installed this, same issue after first connection attempt... please implement a serious fix before closing the issue.

**Comment by BuffaloWill** [comment]
@Storm75 this PR has not been packaged in a new release, it's only merged into master.

Also, this fix is purely aesthetic. It won't impact your ability to login.
