### ISSUE TITLE
Custom the Findings

### ISSUE THREAD

**Issue by marcbyky** [SerpicoProject/Serpico#446]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. ...
2. ...

## Feature Request

Describe the feature and give an example use case

Would it be possible to have more fields for the findings so that it would be possible to mention not only the risk, but also the impact, the status of the vuln, as well as the scope of the finding?

### Example Use Case

As a user, I would like to be able to add the impact of the vulnerability that I found, such as the level of impact from low to high, but also a description of the impact (Increased attack surface for example, it would be a fill in the blank type). I would also like to mention what is the actual status of the vuln, if it is confirmed or if it is certain (means it was not possible to test it due to client request), and finally the scope to mention for example what web pages were affected by a particular vulnerability.

**Comment by BuffaloWill** [comment]
@marcbyky have you tried testing other scoring algorithms? Many such as CVSS have this field.

Also, a UDO (https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Objects) would work.

**Comment by marcbyky** [comment]
Thanks Will,

When are you planning on the next official release ?
