### ISSUE TITLE
Replace spaces in generated report filename

### ISSUE THREAD

**Issue by anantshri** [SerpicoProject/Serpico#447]
# This is a suggestion

Generate Report option generates file based on name provided by the users if name has spaces they are kept as-is. 
I would propose replacing spaces with _ or - to avoid the whole game around spaces being considered as argument seperator at commandline.

Might not be useful in GUI cut and paste environment but if files are handled over CLI it helps.

**Comment by BuffaloWill** [comment]
This makes sense. However, I am going to close the issue. os x/linux can handle this from the CLI  (```find -name "* *.docx" -type f | rename 's/ /_/g'```) or via scripting. Assigning this as a potential feature or a likelihood of being implemented would be false hope. 

We will get it in some of your features soon though =) =)
