### ISSUE TITLE
[Question] Adding new report variables

### ISSUE THREAD

**Issue by r3b00t5** [SerpicoProject/Serpico#453]
So I've got a few fields I need to add to the findings template:
1. Area of Responsibility
2. Verified or Unverified
3. Report Finding ID

As a stopgap, I re-purposed the Assessment Type and Remediation Effort fields as AoR and Verified, respectively.

Is there a guide on how I go about adding them to Serpico?

I know that #340 deals with adding custom fields on the fly, but I'm looking to add it more permanently for my instance.

**Comment by r3b00t5** [comment]
Thanks @sho-luv, is it here? 
https://github.com/SerpicoProject/SerpicoPlugins

**Comment by bahs123** [comment]
@sho-luv is it added in the Serpicoplugins folder? Because even I have same requirement

**Comment by BuffaloWill** [comment]
I am going to track this in https://github.com/SerpicoProject/Serpico/issues/340. I added the addition that the fields should be able to be imported allowing the user to make the changes more permanent.
