### ISSUE TITLE
support for kali 2018.2

### ISSUE THREAD

**Issue by xillwillx** [SerpicoProject/Serpico#454]
newer version of ruby 2.5.1
.deb file installs fine though
vulndb import not working

> ruby scripts/import_vulndb.rb 
Traceback (most recent call last):
	5: from scripts/import_vulndb.rb:8:in `<main>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /opt/Serpico/Serpico/model/master.rb:2:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- data_mapper (LoadError)

**Comment by BuffaloWill** [comment]
@xillwillx, looks like data_mapper gem is not installed. try running

```
bundle install
```

No plans to support Ruby 2.5.1 right now.
