### ISSUE TITLE
Ability to Add Finding Types to the Findings Database

### ISSUE THREAD

**Issue by Simon-Davies** [SerpicoProject/Serpico#459]
## Feature Request

Please add an option to Add Finding Types to the Findings Database.

### Example Use Case

There is no Mobile Assessment Finding Type or IOT Finding Type.

Please add an option so users can add their own Finding Types or add the two above

Thanks in advance.

**Comment by sho-luv** [comment]
This can be done in the config.json file. Not documented well. However you
can simply add finding types to the config.json file and restart serpico.

**Comment by Simon-Davies** [comment]
Thank you. I've got it sorted now :)
