### ISSUE TITLE
variables in libre office

### ISSUE THREAD

**Issue by a0912** [SerpicoProject/Serpico#463]
Hello I have a problem with variables in Libre office. In the template, I put ΩFULL_COMPANY_NAMEΩ for example, in an other template than Default Template- Generic Risk Scoring and variables aren't take into account when I generate a report. Can you help me please ?

**Comment by BuffaloWill** [comment]
Hi @a0912. Serpico does not support LibreOffice. Cheers!

**Comment by a0912** [comment]
okay thank you :) and if I use it on Ubuntu, what do I need to use ? (Sorry I'm new with this)

**Comment by a0912** [comment]
Thank you !!
