### ISSUE TITLE
Findings in differents tables

### ISSUE THREAD

**Issue by a0912** [SerpicoProject/Serpico#468]
Hello I'm new at this, I want to know if somebody has a solution to create differents tables for differents findings for example a table for cross site scripting (xss) , an other table for sql injection ...
 Thanks for your answers

**Comment by Petessss** [comment]
Check out the default templates https://github.com/SerpicoProject/Serpico/tree/master/templates.  https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth - is another good resource.
