### ISSUE TITLE
Associate a name to personal informations

### ISSUE THREAD

**Issue by a0912** [SerpicoProject/Serpico#472]
Hello ! I want to know how can I associate a name to a phone number and an email. For example, when an user select a name, it's directly print his phone number and his email into the report. Thanks for your answers.

**Comment by BuffaloWill** [comment]
@a0912 Serpico can print the consultant information of the current person working on the report. For example adding ``` ΩFULL_COMPANY_NAMEΩ ``` to a template will print the consultants name in the report. However, it is not possible to print another user's information by username.
