### ISSUE TITLE
Generate repport Error

### ISSUE THREAD

**Issue by ihebski** [SerpicoProject/Serpico#473]
while trying to generate the repport I always got this error .
 How can I debug the Serpico to find exactly the mentioned error ?
Thank you 
```
The following error(s) were found in report XML file :

2691:108140: FATAL: Opening and ending tag mismatch: paragraph line 2691 and bullet1
2691:108167: FATAL: Opening and ending tag mismatch: notes line 2691 and paragraph
2691:108257: FATAL: Opening and ending tag mismatch: paragraph line 2691 and bullet1
2691:108284: FATAL: Opening and ending tag mismatch: findings line 2673 and paragraph
2691:199532: FATAL: Opening and ending tag mismatch: paragraph line 2691 and bullet1
2691:199548: FATAL: Opening and ending tag mismatch: findings_list line 38 and paragraph
2691:199610: FATAL: Opening and ending tag mismatch: paragraph line 2691 and bullet1
2691:199626: FATAL: Opening and ending tag mismatch: report line 1 and paragraph
2691:199626: FATAL: Extra content at the end of the document
This is most often because of malformed metamarkup in findings.
```

**Comment by ihebski** [comment]
I have solved the issue ,by limiting the number of findings , is there any idea of how to deal with huge number of findings let's said 200 findings ? 
The parse function seems to fail when parsing a large xml .

**Comment by frisch-raphael** [comment]
Hi ihebski,

From the error, it seems that one of your bullet metacharacter (*= or =*) is misplaced/lacking.
Probably when limiting the number of findings, you deleted the finding containing the misplaced/lacking metacharacters.

**Comment by ihebski** [comment]
@frisch-raphael  I really appreciate your help ,thank you .
Absolutely you are right, after investigating by removing only those three vulnerabilities, everything works well .
```
SSL Certificate Cannot Be Trusted
SSL Certificate Signed Using Weak Hashing Algorithm
SSL Self-Signed Certificate
```
After 2 hours of debugging removing some findings was the solution , at least I have learned some ruby language syntax :) 
Thanks a lot @frisch-raphael :1st_place_medal:

**Comment by frisch-raphael** [comment]
My pleasure :-)
