### ISSUE TITLE
Leading space in user defined variable name causes XML error

### ISSUE THREAD

**Issue by liquidfire228** [SerpicoProject/Serpico#474]
## Bug

If you accidentally leave a leading space in a variable name when defining a user defined variable, upon trying to generate the associated report an error like this will present:

```
The following error(s) were found in report XML file :

34:2: FATAL: StartTag: invalid element name
34:295: FATAL: expected '>'
34:295: FATAL: Opening and ending tag mismatch: udv line 30 and unparseable
42:7: FATAL: Opening and ending tag mismatch: report line 1 and udv
43:1: FATAL: Extra content at the end of the document
This is most often because of malformed metamarkup in findings.
```

Obviously we don't want to have leading spaces in variable names but it is easy to miss that you have one visually and the error message does not give any clues that this is the problem. Finally tracked it down after long debugging session. 

Expected behavior: Either strip out the leading space silently or present an error via javascript validation or server side validation indicating leading spaces are not allowed.

**Comment by BuffaloWill** [comment]
Thanks @liquidfire228. Marking this as verified.

**Comment by BuffaloWill** [comment]
@liquidfire228 landed a fix for this, thanks!
