### ISSUE TITLE
Add a same findings several times

### ISSUE THREAD

**Issue by a0912** [SerpicoProject/Serpico#484]
Hello everybody !  I want to know if it's possible to have a button to add a same finding several times instead of create it several times. Thanks for your answers ! Have a good day

**Comment by BuffaloWill** [comment]
@a0912 could you provide a use case for this feature request? I don't understand the use case for the user.

**Comment by a0912** [comment]
Yes of course 
For example if I detect 2 XSS, I want to have the possibility to go to "add findings from template" and have a button to select 2 XSS instead of check it two times.

**Comment by frisch-raphael** [comment]
I think one slightly more flexible way to do that would be to have a " duplicate  " in the findings actions. Eitheir way, this seems rather easy to implement, and could be useful in a lot of cases.

**Comment by a0912** [comment]
Yes it's exactly what I want to have in my interface
