### ISSUE TITLE
Serpico Wont allow me to generate a report. Error Message Pops up

### ISSUE THREAD

**Issue by stombya** [SerpicoProject/Serpico#485]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. ... I tried generating a report but Serpico doesn't allow me to do that.
It says this: Error!! Check the process dump for the error or turn show_exceptions on to show in the web interface.

2. ... I'm not that good with computer programming only scripting.

## Feature Request

Describe the feature and give an example use case

### Example Use Case

"As a user ..."

**Comment by BuffaloWill** [comment]
Thanks @stombya. What are the error messages shown in the logs?
