### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by websecnl** [SerpicoProject/Serpico#487]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. when attempting to install it says its already installed (Windows 10 ver: 1803)
i tried running as administrator but neither did that work, when i click uninstall on the installer or repair it says that Serpico does not exist (nothing to uninstall error)

## Feature Request

Windows installer Issue

### Example Use Case

Unable to install.

![image error](https://i.gyazo.com/7436510b2e4b374d770446db2d987dee.png)

**Comment by Petessss** [comment]
Is there anything under c:/serpico? Also check under add and remove programs. Is Serpico listed?

**Comment by websecnl** [comment]
i did, there is nothing as C:/Serpico

**Comment by BuffaloWill** [comment]
@websecnl any updates on this? Having an existing Serpico directory or previously installed version seem like the most likely suspect. We have no other reports of this issue from any Windows release. Maybe try downloading the installer again if you still can't get it to work.

**Comment by BuffaloWill** [comment]
Yes, definitely strange. Could you try re-downloading the installer? Also when the installer asks for the installation directory set it to something new.

**Comment by BuffaloWill** [comment]
Also, what version of Windows are you on?

**Comment by websecnl** [comment]
Windows 10 Version 1803 (OS Build 17134.165)

**Comment by Petessss** [comment]
If you look at program and features, do you see Serpico listed?

**Comment by websecnl** [comment]
@Petessss no it's not listed.

Since windows did not work I installed this on a linux vm and than did it through my windows machine browser.
