### ISSUE TITLE
Import from nessus

### ISSUE THREAD

**Issue by bhaizlett123** [SerpicoProject/Serpico#488]
-------------------
## Bug
Describe the issue and steps to reproduce

I have imported a nessus scan, that has all risk levels of vulnerabilities, but when i bring up the list i only see the critical, high and medium, it says 0 for low and informational, which i have about 10 lows and 50 informationals according to nessus report.

Not sure if this is a bug or does something need to be enabled to show them in the list.

**Comment by BuffaloWill** [comment]
Hi @bhaizlett123, Try changing the threshold setting in the configuration (https://127.0.0.1:8443/admin/config) to 0 and re-importing.
