### ISSUE TITLE
Finding markup problem

### ISSUE THREAD

**Issue by a0912** [SerpicoProject/Serpico#489]
I have a problem with finding markup. It doesn't work with the report that I import in Serpico. Can somebody help me ?

**Comment by Petessss** [comment]
Can you please provide more information. There is not much to go on here.

**Comment by Petessss** [comment]
This may help when submitting a bug. 
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. ...
2. ...

### Example Use Case

"As a user ..."
