### ISSUE TITLE
ruby error

### ISSUE THREAD

**Issue by Luis-Filipe** [SerpicoProject/Serpico#491]
Hello,

Please see below what happens, I use Serpico 1.2.1 for MAC high Sierra.

## Bug

>sudo ruby serpico.rb

/Users/root1/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/root1/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from serpico.rb:1:in `<main>'
Carloss-MacBook-Pro:Serpico root1$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin17]

I cannot import Nessus reports, after editing the file config.json:

{
  "port": "8443",
  "use_ssl": true,
  "bind_address": "0.0.0.0",
  "ssl_certificate": "./cert.pem",
  "ssl_key": "key.pem",
  "ldap": false,
  "ldap_domain": "",
  "ldap_dc": "",
  "dread": false,
  "cvss": false,
  "nessusmap": true,
  "burpmap": true,
  "vulnmap": true,
  "finding_types": [
    "Web Application",
    "Business Logic",
    "Network Services",
    "Best Practice",
    "Compliance",
    "Database",
    "Network Internal",
    "Router Configuration",
    "Social Engineering",
    "Physical",
    "Wireless",
    "Network Security",
    "System Security",
    "Logging and Auditing",
    "Imported"
  ],
  "logo": "/img/logo_1.svg",
  "auto_import": true,
  "chart": true,
  "user_defined_variables": [

  ],
  "report_assessment_types": ["Network Internal","External","Web application","Physical","Social engineering","Configuration audit"],
  "threshold": "2",
  "log_file": "./log/serpico.log",
  "show_exceptions": false
}

**Comment by BuffaloWill** [comment]
Hi @Luis-Filipe, your version of Ruby looks incorrect. You will need 2.3.3:

https://github.com/SerpicoProject/Serpico/wiki/Developer-Build
