### ISSUE TITLE
FATAL: xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by Clickb8** [SerpicoProject/Serpico#492]
## Bug
Hi there,
I just tried Serpico, first i would like to thank you for your work, great tool. Now I have a little problem:

On a debian fresh install (stretch), using the deb file (serpico_1.3.0_amd64.deb) and after initializing the database I can't generate a report because of an error

> The following error(s) were found in report XML file :
> 8:37: FATAL: xmlParseEntityRef: no name
> 
> This is most often because of malformed metamarkup in findings.

### Example Use Case

1 - Connect to Serpico
2 - New report, default template
3 - Fill the informations
4 - Add a vuln like XSS in the findings
5 - Click generate report

Maybe am I missing something ? It tells me "no name" but every field is complete so...

![serp](https://user-images.githubusercontent.com/25489005/43069296-055ee044-8e6d-11e8-9929-e05902d885a9.png)

**Comment by frisch-raphael** [comment]
There's probably a " & " in either your findings or your report informations. Can you check that ?
Serpico should encode it though, so this is kinda surprising.

**Comment by Clickb8** [comment]
I have only one finding, it's a pre-complete one, (XSS) that already exists in Serpico DB. No "&" in it apparently.

Finding (XSS base template)
![image](https://user-images.githubusercontent.com/25489005/43187165-0a566c18-8ff1-11e8-9181-f04246efaf6f.png)
Report info
![image](https://user-images.githubusercontent.com/25489005/43187227-2d9d0fce-8ff1-11e8-81a6-2dc8af95c79c.png)

Still the same problem.

**Comment by BuffaloWill** [comment]
Hi @Clickb8! Is this still an issue? Are you using a custom template?
