### ISSUE TITLE
Use string comparison inside a table

### ISSUE THREAD

**Issue by tibillys** [SerpicoProject/Serpico#493]
## Feature request
Hello, can you provide the ability to use string comparison inside a table?

**Comment by BuffaloWill** [comment]
String comparison should work inside of a table.

I would suggest starting with classic string comparison to verify:
https://github.com/SerpicoProject/Serpico/wiki/Parsing-by-Assessment-Type-or-Performing-a-String-Comparison-in-a-Report#classic-string-comparison
