### ISSUE TITLE
Cant edit consultant info

### ISSUE THREAD

**Issue by websecnl** [SerpicoProject/Serpico#495]
## Bug
Describe the issue and steps to reproduce

1. cant find where to edit some of the consultant information.

## Feature Request

Easier access to edit all consultant information.

### Example Use Case

.![info](https://i.gyazo.com/b0d7af2dd0664d0092c8a72a3a5bf209.png)

**Comment by websecnl** [comment]
i still cant edit the business information... it always generates report with the info in the image above and under "Serpico Template Company (STC)" as contracted company.

**Comment by BuffaloWill** [comment]
Hi @websecnl, the business information is contained in the report template you are using. You will need to update your report template to have the correct business information. Only consultant specific information is stored in the Serpico DB, the rest is in the report template.
