### ISSUE TITLE
UDV in for each loop

### ISSUE THREAD

**Issue by diablodaz** [SerpicoProject/Serpico#496]
Is it possible to use a user defined variable within the for each loop? I'm trying to get the job_code variable to appear in the findings for each loop e.g.

¬report/findings_list/findings:::risk>3¬
•	πtitleπ
•	§job_code§

The title appears fine however the job_code UDV does not.

Any ideas?

TIA

**Comment by frisch-raphael** [comment]
Hi diablodaz,

The following should work :

¬report/findings_list/findings:::risk>3¬
•	πtitleπ
•	π/report/udv/job_codeπ
