### ISSUE TITLE
Color riskmatrix

### ISSUE THREAD

**Issue by a0912** [SerpicoProject/Serpico#498]
Hello everybody, I want to create something like this : when I select a level of risk, it colors the matrix case in the right color in the word report.

For example : when I select "critical" on serpico for the risk, when I generate the report, the risk case is in red.

Can somebody help me please ? Thanks for your help !

**Comment by markajbell** [comment]
You should be able just to colour the title red. That means every critical
would be red. Amber for medium and yellow for lows
 mark
