### ISSUE TITLE
Meta Langauge for known hosts issues 

### ISSUE THREAD

**Issue by CharlieMong** [SerpicoProject/Serpico#509]
Serpico Version: 1.3.0 Official Release

So am loving Serpico (Just getting to grips with it for our reporting) however when trying to put the affected hosts into a report template and use it I am getting issues when opening the report with word (Also edited in word). It basically does not output the Affected Hosts.
Have tried multiple variations on this and its bound to be something am missing. 
-------------------
Affected Hosts/URL
¬affected_hosts/paragraph¬ µzzzzµ π.π
÷ π.π ≠
-------------------
Or in a table.
affected hosts
--
¬affected_hosts/paragraph¬π.π ∆
-----------------
Affected Hosts/URL
¬affected_hosts/paragraph¬ µzzzzµ π.π 
ƒcodeƒ π.π
ƒitalicsƒ π.π
•	ƒbulletƒ π.π

÷ π.π ≠

Is this an issue or is my meta off?

**Comment by agreenbhm** [comment]
Here is what I'm using for affected hosts.  It worked for me without issue: 
![image](https://user-images.githubusercontent.com/622379/46814023-d97bb200-cd45-11e8-8e01-67cb86a0190c.png)

**Comment by BuffaloWill** [comment]
Thanks @agreenbhm!! Agreed that should work.
