### ISSUE TITLE
Generate pie chart reports and image scaling issues

### ISSUE THREAD

**Issue by nobodysz** [SerpicoProject/Serpico#518]
Hi , team~

1. Can I generate a report like this into the report?
![image](https://user-images.githubusercontent.com/18529417/46789475-1a3bf100-cd6f-11e8-83b1-3c734510d894.png)

2. The image I inserted in the findings was not automatically scaled to the appropriate size when generating the report, causing the image to be manually scaled each time. If that is, it would be great.

**Comment by BuffaloWill** [comment]
@nobodysz Unfortunately graphs cannot be generated into reports at this time. Cheers!
