### ISSUE TITLE
Make it possible to use multiple scoring types

### ISSUE THREAD

**Issue by Manonnnn4** [SerpicoProject/Serpico#532]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Feature Request

Instead of having to choose one scoring type in the report, it would be very nice to be able to have multiple (so instead of the dropdown list in the report configuration, an checkbox list). I'd like to show both risk and dread category for example.

### Example Use Case

"As a user I want to know both the risk of a finding as the cvss score and the dread category "

**Comment by BuffaloWill** [comment]
@Manonnnn4 Unfortunately this would require significant changes to the code and being realistic not something we are going to get in. It is possible to add a User Defined Object (https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Objects) which you could require a user to fill out with additional scoring for a finding.

**Comment by Manonnnn4** [comment]
@BuffaloWill Thanks, I can understand and respect that.  
I find the wiki page on UDOs a bit difficult to understand. It does not really give me an idea what UDO's can be used for, how (if?) they show up in the webUI when adding findings, and lastly what the different fields do (object type, property name, components). Is there a place that gives a little more guidance on UDO's?
