### ISSUE TITLE
Error performing Developer Build install: 

### ISSUE THREAD

**Issue by dave5623** [SerpicoProject/Serpico#536]
## Bug
When attempting to run the first time script to do a Developer Build setup, I come across error and terminal output:
user@ubuntu:/opt/Serpico$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
user@ubuntu:/opt/Serpico$ uname -a
Linux ubuntu 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
user@ubuntu:/opt/Serpico$ ruby scripts/first_time.rb 
/home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/connection.rb:79:in `initialize': unable to open database file (DataObjects::ConnectionError)
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/connection.rb:79:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:181:in `block in new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:176:in `synchronize'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:176:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:121:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/connection.rb:68:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:251:in `open_connection'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-transactions-1.2.0/lib/dm-transactions/adapters/dm-do-adapter.rb:69:in `open_connection'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:33:in `select'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb:43:in `table_info'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb:18:in `storage_exists?'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:90:in `create_model_storage'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:57:in `upgrade_model_storage'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:73:in `upgrade_model_storage'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:145:in `auto_upgrade!'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:47:in `block in repository_execute'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:64:in `block in each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `block in each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `block in each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:63:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:46:in `repository_execute'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:27:in `auto_upgrade!'
	from /opt/Serpico/model/master.rb:439:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from scripts/first_time.rb:1:in `<main>'

**Comment by BuffaloWill** [comment]
Closing unless this is still an issue.

**Comment by dave5623** [comment]
I gave the installation another shot and I must be doing something wrong? I believe I'm following the instructions on the Developer Build site faithfully though. 

```
user@ubuntu:/opt/Serpico$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
user@ubuntu:/opt/Serpico$ bundle install
Using public_suffix 3.0.3
Using addressable 2.5.2
Using bcrypt 3.1.12
Using bcrypt-ruby 3.1.5
Using bundler 1.17.1
Using dm-core 1.2.1
Using dm-aggregates 1.2.0
Using dm-constraints 1.2.0
Using dm-migrations 1.2.0
Using fastercsv 1.5.5
Using json 1.8.6
Using json_pure 1.8.6
Using multi_json 1.13.1
Using dm-serializer 1.2.2
Using dm-timestamps 1.2.0
Using dm-transactions 1.2.0
Using stringex 1.5.1
Using uuidtools 2.1.5
Using dm-types 1.2.2
Using dm-validations 1.2.0
Using data_mapper 1.2.0
Using data_objects 0.10.17
Using dm-do-adapter 1.2.0
Using do_sqlite3 0.10.17
Using dm-sqlite-adapter 1.2.0
Using filesize 0.2.0
Using temple 0.8.0
Using tilt 2.0.8
Using haml 5.0.4
Using rkelly-remix 0.0.7
Using jsobfu 0.4.2
Using metasm 1.0.3
Using mini_portile2 2.3.0
Using msgpack 1.2.4
Using nokogiri 1.8.1
Using rb-readline 0.5.5
Using robots 0.10.1
Using rex 2.0.11
Using msfrpc-client 1.1.1
Using mustermann 1.0.3
Using net-ldap 0.16.1
Using odle 0.0.8
Using rack 2.0.5
Using rack-protection 2.0.4
Using rubyzip 1.2.2
Using sinatra 2.0.4
Bundle complete! 11 Gemfile dependencies, 46 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
user@ubuntu:/opt/Serpico$ ruby scripts/first_time.rb 
/home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/connection.rb:79:in `initialize': unable to open database file (DataObjects::ConnectionError)
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/connection.rb:79:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:181:in `block in new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:176:in `synchronize'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:176:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:121:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/data_objects-0.10.17/lib/data_objects/connection.rb:68:in `new'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:251:in `open_connection'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-transactions-1.2.0/lib/dm-transactions/adapters/dm-do-adapter.rb:69:in `open_connection'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:33:in `select'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb:43:in `table_info'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb:18:in `storage_exists?'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:90:in `create_model_storage'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb:57:in `upgrade_model_storage'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:73:in `upgrade_model_storage'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:145:in `auto_upgrade!'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:47:in `block in repository_execute'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:64:in `block in each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `block in each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `block in each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/ordered_set.rb:320:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/subject_set.rb:211:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/support/descendant_set.rb:63:in `each'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:46:in `repository_execute'
	from /home/user/.rvm/gems/ruby-2.3.3/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:27:in `auto_upgrade!'
	from /opt/Serpico/model/master.rb:439:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from scripts/first_time.rb:1:in `<main>'
```

**Comment by BuffaloWill** [comment]
Hrm, that might be a permissions error ..  Is the user able to write the opt directory?
