### ISSUE TITLE
Docker Run - Unable to locate docker.sh

### ISSUE THREAD

**Issue by yogisec** [SerpicoProject/Serpico#538]
Error when attempting to run container

1. I went through the docker build process here:
https://github.com/SerpicoProject/Serpico/wiki/Running-Serpico-From-Docker

2. When I attempt to spin up the container using 
docker run --name serpico -p 8443:8443 -v"$(pwd)":/Serpico/db -it serpico

It errors out 'unable to locate docker.sh'

I resolved the issue by copying the docker.sh file into the container pull 537 resolves this issue:
https://github.com/SerpicoProject/Serpico/pull/537

**Comment by BuffaloWill** [comment]
Landed. Thanks @yogisec!
