### ISSUE TITLE
Issue adding Severity to report

### ISSUE THREAD

**Issue by wbbugs** [SerpicoProject/Serpico#540]
I would like to add the CVSS3.0 string and Severity to my report.

Ideally I want to state something like the below:

Critical : SQL Injection
I can add the Title with ΠTitleΠ but I cant seem to find how to add the Severity rating.
---
I would also like to add the CVSS3.0 score like the below:
CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N

Im new to Serpico and am learning but would appreciate any help.
Thanks in advance

**Comment by BuffaloWill** [comment]
Hi @wbbugs, check the default templates directory. There is an example of a CVSS report that should have this. cheers!
