### ISSUE TITLE
Request for list of all template variables

### ISSUE THREAD

**Issue by chppppp** [SerpicoProject/Serpico#541]
## Feature Request

I am creating a template. Is there a list that exists of all the variables that can be used eg) ΩCONSULTANT_NAMEΩ

**Comment by BuffaloWill** [comment]
https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth#reporting-components

Also for findings:
https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth#finding-components

**Comment by chppppp** [comment]
Thank you!!!! I thought I looked through the wiki but perhaps I was a little tired :)

**Comment by BuffaloWill** [comment]
np :+1:
