### ISSUE TITLE
hyperlink in finding table

### ISSUE THREAD

**Issue by MichaelLucas** [SerpicoProject/Serpico#545]
Hello,

I usually add manually an hyperlink for each finding in the "finding table" that point to the detailed finding chapter in the same document. 
Do you think this could be automated in Serpico?

**Comment by BuffaloWill** [comment]
@MichaelLucas thank you for submitting an issue. I am not sure the scale of effort to do this. It is FOSS ... so I always side with it is possible given enough effort. 

The main unknowns for the team would be (a) how does office handle internal hyperlinks within a document and (b) how would we link these two components in an automated fashion on report generation. 

I am going to close the issue. Someone can reopen later if there is a desire to take this on.
