### ISSUE TITLE
Export findings to XML/JSON? 

### ISSUE THREAD

**Issue by chppppp** [SerpicoProject/Serpico#549]
## Feature Request

In accordance with CSC20 audits (https://en.wikipedia.org/wiki/CSC_Version_6.0 section 20.7) findings must be available in machine readable formats. Can Serpico export findings into XML/JSON format?

**Comment by BuffaloWill** [comment]
Hi @chppppp! There is a script in the scripts directory (https://github.com/SerpicoProject/Serpico/blob/master/scripts/export_reports.rb) to export all reports and findings as JSON.
