### ISSUE TITLE
installation failure on Kali 2019.1

### ISSUE THREAD

**Issue by superuser5** [SerpicoProject/Serpico#559]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. using kali 2019.1
2. running git clone https://github.com/SerpicoProject/Serpico/
3. cd /root/Serpico/scripts
4. root@kali:~/Serpico/scripts# bash serpicoInstall.sh 
gpg: key 3804BB82D39DC0E3: 47 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Downloading https://github.com/rvm/rvm/archive/1.29.7.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.7/1.29.7.tar.gz.asc
gpg: Signature made Thu 03 Jan 2019 05:01:48 PM EST
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/usr/local/rvm/archives/rvm-1.29.7.tgz'
Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.
  * Please do NOT forget to add your users to the rvm group.
     The installer no longer auto-adds root or users to the rvm group. Admins must do this.
     Also, please note that group memberships are ONLY evaluated at login time.
     This means that users must log out then back in before group membership takes effect!
  * No new notes to display.

gpg: key 105BD0E739499BDB: 5 signatures not checked due to missing keys
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: 105 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 2
gpg:              unchanged: 2
The user `root' is already a member of `rvm'.
The user `root' is already a member of `rvm'.
Required ruby-2.3.3 is not installed.
To install do: 'rvm install "ruby-2.3.3"'
/bin/bash: line 9: /home/root/.bashrc: No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl1.0-dev is already the newest version (1.0.2q-2).
The following packages were automatically installed and are no longer required:
  libboost-program-options1.67.0 libboost-python1.62.0 libboost-serialization1.67.0 libboost-system1.62.0
  libboost-test1.67.0 libboost-thread1.62.0 libboost-timer1.67.0 libcgal13 libcharls1 libcrypt2 libfcgi-bin
  libfcgi0ldbl libicu-le-hb0 libicu60 liblwgeom-2.5-0 liblwgeom-dev libmozjs-52-0 libpoppler80 libpyside1.2
  libpython3.6 libpython3.6-dev libpython3.6-minimal libpython3.6-stdlib libqca2 libqca2-plugins
  libqgis-analysis2.18.25 libqgis-analysis2.18.28 libqgis-core2.18.25 libqgis-core2.18.28 libqgis-customwidgets
  libqgis-gui2.18.25 libqgis-gui2.18.28 libqgis-networkanalysis2.18.25 libqgis-networkanalysis2.18.28
  libqgis-server2.18.25 libqgis-server2.18.28 libqgispython2.18.25 libqgispython2.18.28 libqtwebkit4 libqwt6abi1
  libradare2-3.1 libsfcgal1 libshiboken1.2v5 libspatialindex4v5 libspatialindex5 libwhisker2-perl python-cycler
  python-kiwisolver python-matplotlib python-matplotlib2-data python-nassl python-owslib python-pyproj
  python-pyside.qtcore python-pyside.qtgui python-pyside.qtnetwork python-pyside.qtwebkit python-pyspatialite
  python-qgis python-qgis-common python-qt4-sql python-shapely python-subprocess32 python3.6 python3.6-dev
  python3.6-minimal qt4-designer ruby-dm-serializer ruby-faraday ruby-geoip ruby-libv8 ruby-ref ruby-therubyracer
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Sun 30 Dec 2018 05:44:46 AM EST
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.
  * Please do NOT forget to add your users to the rvm group.
     The installer no longer auto-adds root or users to the rvm group. Admins must do this.
     Also, please note that group memberships are ONLY evaluated at login time.
     This means that users must log out then back in before group membership takes effect!

Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: https://opencollective.com/rvm/donate

Required ruby-2.3.3 is not installed.
To install do: 'rvm install "ruby-2.3.3"'
RVM reloaded!
Warning, new version of rvm available '1.29.7', you are using older version '1.29.7-next'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: kali/kali-rolling/x86_64/ruby-2.1.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for kali.
Removing undesired packages: libssl1.1...
Error running 'requirements_debian_libs_remove libssl1.1',
please read /usr/local/rvm/log/1554791077_ruby-2.1.5/package_remove_libssl1.1.log
Requirements installation failed with status: 100.
Required ruby-2.1.5 is not installed.
To install do: 'rvm install "ruby-2.1.5"'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
gcc is already the newest version (4:8.3.0-1).
libsqlite3-dev is already the newest version (3.27.2-2).
libxml2-dev is already the newest version (2.9.4+dfsg1-7+b3).
libxslt1-dev is already the newest version (1.1.32-2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-1).
The following packages were automatically installed and are no longer required:
  libboost-program-options1.67.0 libboost-python1.62.0 libboost-serialization1.67.0 libboost-system1.62.0
  libboost-test1.67.0 libboost-thread1.62.0 libboost-timer1.67.0 libcgal13 libcharls1 libcrypt2 libfcgi-bin
  libfcgi0ldbl libicu-le-hb0 libicu60 liblwgeom-2.5-0 liblwgeom-dev libmozjs-52-0 libpoppler80 libpyside1.2
  libpython3.6 libpython3.6-dev libpython3.6-minimal libpython3.6-stdlib libqca2 libqca2-plugins
  libqgis-analysis2.18.25 libqgis-analysis2.18.28 libqgis-core2.18.25 libqgis-core2.18.28 libqgis-customwidgets
  libqgis-gui2.18.25 libqgis-gui2.18.28 libqgis-networkanalysis2.18.25 libqgis-networkanalysis2.18.28
  libqgis-server2.18.25 libqgis-server2.18.28 libqgispython2.18.25 libqgispython2.18.28 libqtwebkit4 libqwt6abi1
  libradare2-3.1 libsfcgal1 libshiboken1.2v5 libspatialindex4v5 libspatialindex5 libwhisker2-perl python-cycler
  python-kiwisolver python-matplotlib python-matplotlib2-data python-nassl python-owslib python-pyproj
  python-pyside.qtcore python-pyside.qtgui python-pyside.qtnetwork python-pyside.qtwebkit python-pyspatialite
  python-qgis python-qgis-common python-qt4-sql python-shapely python-subprocess32 python3.6 python3.6-dev
  python3.6-minimal qt4-designer ruby-dm-serializer ruby-faraday ruby-geoip ruby-libv8 ruby-ref ruby-therubyracer
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.
fatal: destination path '/opt/Serpico-Dev' already exists and is not an empty directory.
Required ruby-2.3.3 is not installed.
To install do: 'rvm install "ruby-2.3.3"'

## Feature Request

Describe the feature and give an example use case

### Example Use Case

"As a user ..."

**Comment by BuffaloWill** [comment]
@superuser5 I've updated `SerpicoInstall.sh` to use the correct version of Ruby in the build; thanks. You need to run `rvm install 2.3.3` to get the correct version of Ruby before building.

It is recommended to use the Developer Instructions here to build from master:

https://github.com/SerpicoProject/Serpico/wiki/Developer-Build

Cheers!
