### ISSUE TITLE
"Not empty" condition

### ISSUE THREAD

**Issue by Adrion** [SerpicoProject/Serpico#560]
Hi, is there anyway to test if a variable or user defined one is not empty ? 
I checked into issues and wiki and only find integer testing : [Meta language](https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth)

As I use the default web application template I'd like to add extra condition before showing empty sections like Remediation or references if there is any. 

Many thanks for this tool !

**Comment by BuffaloWill** [comment]
@Adrion unfortunately there is not a built-in easy way to do this that I know of. 

It could be done with https://github.com/SerpicoProject/Serpico/wiki/Serpico-Meta-Language-In-Depth#xslt-code-block-symbol but that requires an advanced understanding of XSLT.

**Comment by Adrion** [comment]
That's what I thought, I'll check XSLT blocks. Mozilla seems to have a decent XSLT [documentation](https://developer.mozilla.org/en-US/docs/Web/XSLT/Element) :) 

Thanks !
