### ISSUE TITLE
Update ruby version compatibility

### ISSUE THREAD

**Issue by noraj** [SerpicoProject/Serpico#563]
## "Feature" Request

Please update to a more recent version of ruby like 2.6.3.

### Reason

- 2.3.x branch is EOL, no more fix since a long time and no more security updates since EOL, in fact no more **anything**. https://www.ruby-lang.org/en/downloads/branches/ EOL since 2019-03-31
- 2.3x ruby fails to build on modern up to date distros https://github.com/rbenv/ruby-build/issues/1309
- For both previous reason using 2.3.3 is discouraged, unwanted and make installing Serpico very difficult and discouraging.
- We need 2.6.x compatibility, right now on newer reason `msfrpc-client` is failing to build. #424

**Comment by noraj** [comment]
PR https://github.com/SerpicoProject/Serpico/pull/564

**Comment by BuffaloWill** [comment]
@noraj Thank you for the issue and the PR. I need to do more testing to make sure we can make the jump to 2.6.3. It seems likely but will require more testing.

**Comment by noraj** [comment]
@BuffaloWill Of course I understand.

**Comment by artis3n** [comment]
Any updates on this?

**Comment by BuffaloWill** [comment]
Landed.
