### ISSUE TITLE
Error in template

### ISSUE THREAD

**Issue by BlAd373** [SerpicoProject/Serpico#573]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

Error in template
Error with a ∞ character : character without pair between :
π, Low Risk Findings, ¬, report/, findings_list, /, findings:::, risk&lt;2:::risk&gt;0, ¬, πtitleπ,
and
π, EFFORT, π, Informational Findings, ¬, report/, findings_list, /, findings:::, risk&lt;1, 

ΩFULL_COMPANY_NAMEΩ
ΩREPORT_NAMEΩ
ΩDATEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩCONTACT_CITYΩ
ΩCONTACT_STATEΩ
ΩCONTACT_ZIPΩ
ΩCOMPANY_WEBSITEΩ
ΩCONTACT_NAMEΩ
ΩCONTACT_TITLEΩ
ΩCONTACT_PHONEΩ
ΩCONTACT_EMAILΩ
ΩCONSULTANT_NAMEΩ
ΩCONSULTANT_TITLEΩ
Ω CONSULTANT_PHONEΩ
Ω CONSULTANT_EMAILΩ
ΩDATEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
ΩSHORT_COMPANY_NAMEΩ
¬report/findings_list/findings:::CVSS_Total&gt;0¬
	¬report/findings_list/findings:::risk&gt;3¬
		πtitleπ
		πEFFORTπ
		¬report/findings_list/findings:::risk&lt;4:::risk&gt;2 ¬
			πtitleπ
			πEFFORTπ
			¬report/findings_list/findings:::risk&lt;3:::risk&gt;1¬
				πtitleπ
				πEFFORTπ
				¬report/findings_list/findings:::risk&lt;2:::risk&gt;0¬
					πtitleπ
					∞  ←

**Comment by BuffaloWill** [comment]
@BlAd373 unfortunately we do not triage report templates through Github. You can try the Slack channel for support if you are still having trouble. Also, the UI allows you to check for potential errors in your template for self help.
