### ISSUE TITLE
Update Dockerfile and Docker instructions on the wiki

### ISSUE THREAD

**Issue by artis3n** [SerpicoProject/Serpico#578]
The README installation instructions include `Running Serpico From Docker [NEEDS TO BE UPDATED]`. I recently set up a working Dockerfile for my fork of Serpico. If the maintainers are interested, I could push up a PR with fixes to the Dockerfile and make updates to the Docker installation wiki page. I can't link my fork here, unfortunately. Here's the Dockerfile in whole. `docker.sh` is unmodified.

```dockerfile
FROM ruby:2.3.8
LABEL maintainer="You :)"

RUN apt-get update && apt-get -y upgrade
# Nokogiri dependencies. Nokogiri is one of the gems used by the project.
RUN apt-get install -y libreadline-dev libxml2 libxml2-dev libxml2-utils libxslt-dev
RUN apt-get install -y build-essential

ENV SRP_ROOT /Serpico
# Answer the user prompt questions in `first_time.rb`.
ENV SRP_ADMIN Administrator
ENV SRP_FINDINGS yes

RUN mkdir $SRP_ROOT
WORKDIR $SRP_ROOT

COPY . $SRP_ROOT
COPY ./docker/docker.sh scripts/docker.sh

# Update bundler and install dependencies
RUN gem update --system
RUN gem install bundler
RUN bundle install

# Allow DB to be on a shared volume
VOLUME ["$SRP_ROOT/db"]
EXPOSE 8443

CMD ["bash", "scripts/docker.sh"]
```

`ruby:2.3.8` is needed to fix an error with `bundler`. Need to use bundler 2.x and cannot on 2.3.3/2.3.5.

**Comment by BuffaloWill** [comment]
The docker details have been added to :+1: 

https://github.com/SerpicoProject/Serpico/wiki/Running-Serpico-From-Docker
