### ISSUE TITLE
Findings revision history

### ISSUE THREAD

**Issue by ccammilleri** [SerpicoProject/Serpico#58]
It would be useful to see and compare revision histories of an edited finding. We often tweak our existing findings and it would be nice to see those changes. Similar to a wiki revision history, highlighting what as changed recently.

**Comment by BuffaloWill** [comment]
@ccammilleri - Great idea. AFAIK sqlite doesn't support true revision commit history. We could staple it on by storing each revision of the finding. Taking that approach, IMO proposed steps:

- Add support in model for finding history
- Add support to serpico.rb to store the revision after each submission
- Create "presentation" layer

As a first step we could create the presentation as a script, atleast the data would be stored.

**Comment by Petessss** [comment]
this would be great for the new plugin design.

**Comment by BuffaloWill** [comment]
move to plugins
