### ISSUE TITLE
[Feature Request] Targets list

### ISSUE THREAD

**Issue by ReverseBrain** [SerpicoProject/Serpico#585]
It would be nice to have a loop for each penetration test target to fill a table in the introduction section of the report. Something like this:

| Target |
| -- |
| 1.2.3.4 |
| 5.6.7.8 |
| 1.1.1.1 |
| 8.8.8.8 |

**Comment by gabu-b** [comment]
I think you can do it using UDO's. 
Look: https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Objects

**Comment by BuffaloWill** [comment]
Agreed, UDO's are the best way to solve this.
