### ISSUE TITLE
Problems running the first time script

### ISSUE THREAD

**Issue by bluebird008** [SerpicoProject/Serpico#587]
# Please fill out the Bug Form or Feature Request Below

-------------------
## Bug
Describe the issue and steps to reproduce

1. I am using parrot linux 5.14
2. I followed the installation part , and when I ran the command 
"ruby scripts/first_time.rb"

It shows this problem

"
Traceback (most recent call last):
	5: from scripts/first_time.rb:1:in `<main>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /home/neobullets/Serpico/model/master.rb:2:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- data_mapper (LoadError)

"

Please suggest What to do .

**Comment by beedaaa** [comment]
I get the same traceback with ubuntu. Have you found a solution in the meantime? :D

**Comment by BuffaloWill** [comment]
Hi @bluebird008 and @beedaaa! I just did a fresh install of Serpico on an Ubuntu 18.04 VM and did not run into this issue. 

FWIW your error looks to be that `data_mapper` did not install correctly. Please try running `bundle install` from your Serpico directory to make sure all gems have been properly installed.

**Comment by beedaaa** [comment]
okay thanks, will do that.

**Comment by beedaaa** [comment]
@bluebird008 Hi there, I've solved the problem by re-installing rvm, try that. easier then I tought it would be (I'm not a pro). 

anyways, thanks y'all for the help :)

**Comment by BuffaloWill** [comment]
Glad to hear it :+1:
