### ISSUE TITLE
[Feature Request] Add a <<company_domain>> field for use globally

### ISSUE THREAD

**Issue by deadjakk** [SerpicoProject/Serpico#588]
## Feature Request

Create a <<company_domain>> field for the client's active directory domain field.
I think this gets used even more than the website field would be and re-purposing the website field sometimes leaves newer users confused and it's a bit intuitive. 

Alternatively, while there are user defined objects, those are dependent on the sections being defined within the report template. If there were user defined VARIABLES that could be used just like the other "<<X>>" variables (independent of markup requirements), that would be even better.

### Example Use Case

"...was found within the <<company_domain>>..."

**Comment by BuffaloWill** [comment]
@deadjakk there are currently user defined variables:

https://github.com/SerpicoProject/Serpico/wiki/User-Defined-Variables

You should be able to add a `company_domain` variable for use.
