### ISSUE TITLE
newlines disappear from findings in custom template 

### ISSUE THREAD

**Issue by YousefAlkhulaif** [SerpicoProject/Serpico#590]
# newlines disappear from findings in custom template 

-------------------
## Bug
1. while writing in the findings section, the newlines disappear after generating the report in .docx
2. also in the company name section, the spaces disappear as well.

**Comment by BuffaloWill** [comment]
Hi @YousefAlkhulaif, we don't troubleshoot templates via GH issues. Please post in the Slack channel and someone maybe able to help you. Cheers!

**Comment by YousefAlkhulaif** [comment]
i don't have an account, can u invite me?
