### ISSUE TITLE
Can't pull Docker image

### ISSUE THREAD

**Issue by doc-sewell-alpine** [SerpicoProject/Serpico#591]
## Bug
Following instructions from the documentation...

1. docker pull serpico/serpico:v1.3.1.0
Error response from daemon: manifest for serpico/serpico:v1.3.1.0 not found: manifest unknown: manifest unknown

I see that v1.3.1.0 was released a couple of hours ago.  Can I infer from this that the Docker image hasn't made it to Docker Hub yet?

**Comment by BuffaloWill** [comment]
Good find. I just updated the documentation and the release page to include the proper link.

**Comment by BuffaloWill** [comment]
This is a work in progress. Thank you for the fast feedback =)!

**Comment by doc-sewell-alpine** [comment]
Got me one step further:

`root@malacandra:/opt/SERPICO# docker run --name serpico -p 8443:8443 -v"$(pwd)":/Serpico/db -it serpico
Unable to find image 'serpico:latest' locally
docker: Error response from daemon: pull access denied for serpico, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
root@malacandra:/opt/SERPICO# docker run --name serpico -p 8443:8443 -v"$(pwd)":/Serpico/db -it serpico:release-1.3.1.0
Unable to find image 'serpico:release-1.3.1.0' locally
docker: Error response from daemon: pull access denied for serpico, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`

**Comment by BuffaloWill** [comment]
The command is close, but still missing the tag, try this:

```
sudo docker run --name serpico -p 8443:8443 -v"$(pwd)":/Serpico/db -it serpico/serpico:release-1.3.1.0
```

I just updated the Wiki. Thank you being a guinea pig.

**Comment by doc-sewell-alpine** [comment]
Looks like we posted at about the same time!  I saw yours just after I posted mine above.
