### ISSUE TITLE
[Bug] Current Findings broken on v1.3.2-pre

### ISSUE THREAD

**Issue by artis3n** [SerpicoProject/Serpico#594]
## Bug

Can't show the original report, however on an existing report with 8 findings, after merging in the code from master, the Current Findings page now displays no chart and 0 findings aggregated. The individual findings do appear below in the list. They do correctly generate in the report. It looks like it's just the view on Current Findings.

![image](https://user-images.githubusercontent.com/6969296/73873779-427f1700-4820-11ea-8724-fc54434ebe71.png)

Didn't dig into it that deeply, but this should help point to the bug location:

![image](https://user-images.githubusercontent.com/6969296/73873813-5591e700-4820-11ea-8c55-1a9e1565ace4.png)

**Comment by BuffaloWill** [comment]
The Docker dev build for v1.3.2-pre just finished, I will dig into this now.

**Comment by BuffaloWill** [comment]
@arisada could you verify that the scoring algorithm for your report matches the one you imported? I believe this should fix the findings not being listed. If not, what is the scoring you have set for your report? 

The chart not appearing looks to be a different issue, looking at that now.

**Comment by arisada** [comment]
> @arisada could you verify that the scoring algorithm for your report matches the one you imported? I believe this should fix the findings not being listed. If not, what is the scoring you have set for your report?

Hi, I think you mentioned me instead of @artis3n by mistake.

**Comment by BuffaloWill** [comment]
@arisada - You are correct, sir. Fixed. Sorry!

**Comment by artis3n** [comment]
No problem - 

Under administrative config, the Risk Scoring Algorithm is CVSSv3

The report's Scoring Type is CVSSv3

I made this example out of arbitrary finding templates - 

![image](https://user-images.githubusercontent.com/6969296/73886472-b4af2600-4837-11ea-9ed9-0fdf01eee713.png)

**Comment by artis3n** [comment]
> this should fix the findings not being listed

I think I wasn't clear in my issue description. The findings do appear - it is only the chart and the severity categories numbers next to the chart (including the informational category name) that are missing.

**Comment by artis3n** [comment]
I will say I like the UI updates overall :)

**Comment by BuffaloWill** [comment]
> The findings do appear, as in the screenshot in my last comment
Ok, excellent.

I just pushed a fix to hopefully fix the graph issue

**Comment by artis3n** [comment]
That did fix the graph, although I asked a question on the commit regarding `informational` / `very low` no longer being a thing.

**Comment by BuffaloWill** [comment]
Yes that was intentional for now. I will create an issue to track that. I didn't like the inconsistent behavior between different scoring algorithms so I went the immediate fix until we can get it more consistent.
